### ISSUE TITLE
JobSeekervn - Senior Back-end Developer  - FT - HCM

### ISSUE THREAD

**Issue by hahoainhi** [golang-vietnam/job_board#100]
## Location

* Saigon, Vietnam
* Remote, full-time

## Salary Expectation

* $1600 - $2500/month 

## Requirements
* Be able to write well-designed, testable, and efficient code, and have extensive experience in writing unit tests and acceptance tests;
* In-depth knowledge of at least one of the following programming languages: Java, Go, Scala, and Python. The experience of using front-end frameworks such as Angular is very useful;
* Have a solid knowledge of at least one NoSQL database (such as Mongo) and containerization and orchestration tools (such as Docker and Kubernetes);
* Have a good understanding of functional and reactive programming paradigms, distributed and parallel processing, microservice architecture and event-driven architecture;
* Skills in at least one public cloud provider (such as GCP, AWS or Azure);
* Highly appreciate the basic knowledge of data engineering and machine learning systems;
* Proven ability to analyze, troubleshoot, and accelerate software implementation;
* Track record with practical experience in modern software engineering methods (preferably more than 4 years).

### Responsibilities
* Self-managing and contributing to the product development activities including both internal projects and joint development projects;
* Conducting end-to-end analysis that includes data gathering and requirements specification, analysis, and ongoing deliverables;
* Writing back-end APIs in Go to manage automated data analytics and machine learning pipelines and training systems, and serve machine learning models on top of Kubernetes;
* Developing and optimizing data analysis and transformation Spark applications in Scala/Python;
* Working with the Product and Data Science teams to brainstorm, design the architecture, evaluate technologies, implement POCs, benchmark and productions the ideas;
* Designing and developing high-level SDKs, sample codes in Python/Java on top of auto-generated gRPC APIs of the platform;
* Building and testing in local/development environment, containerizing and deploying applications or services to Kubernetes using Helm charts and GitOps tools;
* Working with the Sales and Marketing team to understand the requirements and support our clients;
* Mentoring and providing training to associate/junior software engineers and interns, motivating them to reach the next level;
* Participating in technical content writing. This may be in the form of product documentation, blog articles highlighting new features and use cases, as and when the need arises;
* Understanding and advocating our long-term vision while working with the management and product teams to define and adapt the same; and
* Contributing to the evangelization of our product and our culture internally and externally

### Why it would be awesome to work with us
* Laptop provided
* 13th months salary 
* Health Insurance

### Contact
Skype: hahoainhi
Email: nhiha@jobseeker.vn

**Comment by fuatto** [comment]
@hahoainhi bạn sửa lại dùm mình title cho đúng format nha, có thể tham khảo các issue khác được accept, không sẽ không lên data trên page được đâu

**Comment by hahoainhi** [comment]
@fuatto Cảm ơn admin đã nhắc nhở. Mình đã sửa lại nha.
