### ISSUE TITLE
Prime Data - Senior Python/Golang Developer - FT - HCM

### ISSUE THREAD

**Issue by Angietran** [golang-vietnam/job_board#101]
## Location

* Saigon, Vietnam

## Salary Expectation

* Range (1,500-2,500)

## Requirements
* 3+ years Go/Python experience
* Experience with developing complex distributed software systems and quality deployment and system reliability.
* Familiarity with large-scale distributed storage and database systems (SQL or NoSQL, e.g. Postgres, Cassandra, Clickhouse, Redis, Elasticsearch)
* Solid grasp on good software engineering practices such as code reviews, deep focus on quality and documentation
* Integration patterns knowledge & Enterprise integration experience,
* Experience with delivering data-oriented solutions in the recent jobs (DW, BI, ETL, Hadoop, etc), cloud technologies such as GCP, AWS.
* Basic knowledge of Internet security, authentication (HTTP Basic, OAuth, …), data security and privacy, GDPR, encryption data at-rest/in-transit.

## Good to have
* Martech experience ( DMPs, DSP, Emails, CDP, CDXP … )
* Work experience in B2B SaaS in online retail/e-commerce analytics, marketing.
* Work experience in engineering team in retail/commerce companies

## Responsibilities
* Team-work with EM, PO/PM, FE engineers, DE/DS & play an important role in developing the backend of the 1st awesome Customer Data Analytics & eXperience platform made-in Vietnam, with our experienced & passionate team.
* Participating effectively in our Agile/SCRUM process, in software architecture design, deliverable sprints, code reviews and enhancements with the team, etc. as well as proposing new alternatives to existing tech and design solutions.
* Designing maintainable, testable code with high test coverage requirements.
* Creating integration and acceptance test coverage to new features and deployment

## Why it would be awesome to work with us
* Work & learn from domain experts in Scale Distributed Data, AI/ML and Martech 
* Experience with deep tech business going global
* Agile & growth oriented working environment

## Contact

Homepage: primedata.ai
Email: hr@primedata.ai
Phone: 0908 426007
Skype: angie_tran84

**Comment by fuatto** [comment]
@Angietran bạn sửa lại dùm mình title cho đúng format nha, có thể tham khảo các issue khác được accept, không sẽ không lên data trên page được đâu
