### ISSUE TITLE
FINSO - Backend Developer Golang - HCMC - FT

### ISSUE THREAD

**Issue by DiepTrucTran** [golang-vietnam/job_board#105]
## Location

* Saigon, Vietnam

## Salary Expectation

* $1,500 - $2,200

## Requirements

- At least 2 year of experience in backend development with Golang
- Expert in Databases SQL & NoSQL
- Expert in designing and implementing scalable REST APIs
- Experience in Software architecture, system analysis, design patterns, and
- unit testing
- Good understanding of the software development process
- Familiar with multi thread
- Good communications skills
- Quick adaptability and a hunger for knowledge
- Can work independently and in a dynamic team environment

### Responsibilities
- Design and write with the cutting edge Golang to improve the availability. Basic knowledge about DevOps, using Kubenetes is a plus
- scalability, latency, and efficiency
- Engage in service capacity and demand planning, software performance
- analysis, tuning and optimization
- Work closely with infrastructure team in building and scaling back-end
- services as well as performing root cause analysis investigations
- Design, build, analyze and fix large-scale systems
- Debug and modify complex, production software

### Contact

Email: truc.tran@finso.com.vn
Phone number: 0902910097 - Ms. Trúc

**Comment by fuatto** [comment]
@DiepTrucTran bạn sửa lại dùm mình title cho đúng format nha, có thể tham khảo các issue khác được accept, không sẽ không lên data trên page được đâu
