### ISSUE TITLE
Software Architect _ Remote _ 5000 USD

### ISSUE THREAD

**Issue by Tuannd131996** [golang-vietnam/job_board#106]
## Vietnam

* Saigon, Vietnam
* Remote

## Salary Expectation

* Up to  5000 $ + Stock option

## Requirements

- Maintain overall industry knowledge on latest trends, technology, etc. and demonstrate forward thinking around how technology can support where the organization is going. 
• Act as a Subject Matter Expert to the organization for end-to-end architecture of edge computing platform 
• Assist in the development of technology roadmaps 
• Take a hands-on approach to development, review product work, including detailed code from other team members, and provide technical feedback as and when needed 
• Create and maintain documentation of architecture solutions, such as whitepapers, reference architectures, implementation diagrams, product backlog, user story etc. and relevant systems, procedures, and processes. 
• Drive deep architectural discussions in a collaborative fashion to ensure solutions are designed for successful and automated deployment 
• Design the appropriate controls and safeguards to reduce the risk of technology or security breaches and protect sensitive company and/or customer information

## Skills
. Master or Bachelor's degree in Computer Science or related discipline 
• At least 8 years of experience in designing and implementing software applications 
• At least 2 years of experience as Software Architect or similar role 
• Solid experience with microservices and containers (Docker, Kubernetes, Snap, etc.) 
• Significant experience in C/C++/C#, **Golang**, Python, HTML5, and CSS3 
• Experience in designing/implementing **REST** and RPC (using gRPC) APIs 
• Experience with end-to-end data pipeline design (InfluxDb, Grafana, etc.) 
• Experience with **NoSQL** (Redis, etc) and SQL databases (MySQL, PostgreSQL, etc) 
• Experience in building secure APIs with security technologies (Digital certificates, IAM, OAuth) and best practices 
• Experience with distributed version control system such as git, github 
• Experience with IoT SDKs/frameworks such as EdgeX Foundry is preferred 
• Good understanding of **Linux OS** and package management (Debian, etc.) 
• Experience of working and setting up **Agile/DevOps** development environment (CI/CD pipeline, automated testing, product backlog, user story, sprint planning, etc.)
Good knowledge in SDLC tools like Jira, Bitbucket and confluence 
• Excellent communication and problem-solving skills 

### Must Have
- Experience with **Golang**
- Solid understand about DOcker, Kubernetes

### Ideally

* Experience with **Startup**

### Contact

Email: tuanchelsea131@gmail.com
Skype: live:1d4b783f3e768750
Whatsapp: 0377470526

**Comment by fuatto** [comment]
@Tuannd131996 phiền bạn sửa lại title + format của JD cho giống với mẫu vì nếu không sẽ không lên được web golang.org.vn đâu (có thể xem mấy jobs accepted)
