### ISSUE TITLE
A French StartUp - TechLead - Ho Chi Minh city - FT

### ISSUE THREAD

**Issue by lamducduong184** [golang-vietnam/job_board#115]
## Location

* Saigon, Vietnam
* FullTime

## Salary Expectation
Minimum 3000$ 
* 

## Requirements
RESPONSIBILITIES
- You will be playing a key role in driving our technical and product roadmap
- You will be solving technical problems at a very large scale using the latest cutting-edge technologies
- You will be leading a team of talented developers responsible for refining existing functionality of our PaaS platforms, and developing new features to serve millions of users in real-time
MUST-HAVE EXPERIENCE
- A university degree (BS, MS, or PhD is a plus) in Computer Science or related fields
- Strong understanding of data structures, algorithms, concurrency, object-oriented programming
- 8 to 10+ year of experience with Golang and/or C++/Java
- 4+ years of experience with relational databases and NoSQL/distributed databases
- 3+ years of experience with container-based architecture (Docker/Kubernetes)
- 2 to 10 years of experience with Protobuf/gRPC, OpenAPI, and REST
- Deep understanding of microservices architecture, concepts and how to implement them
- Highly skilled in designing and developing low latency, high availability applications
- Good level of English both verbal and written
NICE TO HAVE
- 2+ years of experience with devops: CI/CD, metrics, logging, monitoring/alerting
- Experience working in Cloud environments, e.g., gcp, aws
- Experience working with Kafka & ElasticSearch
- Ability to learn quickly and work in a fast-paced environment
- Skills and knowledge of digital advertising and digital marketing
- Good knowledge of AdTech solutions and media industry
WHY YOU’LL LOVE US
- Above-market salary
- Working with the lastest cutting-edge technologies (in big data, machine learning and cloud)
- Opportunity to grow and develop your core skills
- Fully paid health-care package

### Contact

Homepage: https://www.facebook.com/duong.lam.1044/
Email: lamducduong184@gmail.com (0942492607)

**Comment by fuatto** [comment]
@lamducduong184  ,phiền bạn sửa lại nội dung trong hình thành chữ nhé, để lên được web golang.org.vn

**Comment by lamducduong184** [comment]
Mình đã edit lại như bạn hướng dẫn rồi. Many thanks!
