### ISSUE TITLE
Golang back-end Developer

### ISSUE THREAD

**Issue by Linh0401** [golang-vietnam/job_board#118]
## Location

* Hà Nội, Vietnam
* 

## Salary Expectation

* $1500- 3000$/month 
## Requirements

Có kinh nghiệm làm việc với Golang 1 - 1.5 năm.
Có tư duy sáng tạo khi nghiên cứu giải pháp để giải quyết vấn đề.
Có tư duy logic, thuật toán tốt.
Sở hữu tinh thần làm việc của startup: chủ động, chịu khó học hỏi, có trách nhiệm trong công việc.
Hiểu và dùng được các công cụ CI/CD đã được dựng sẵn.

### Responsibilities

Xây dựng hệ thống index dữ liệu on-chain trong thời gian thực.  
Xây dựng các bộ chuyển đổi dữ liệu từ on-chain của các nền tảng blockchain như ethereum, binance smart chain sang dạng có thể đọc và lưu trữ được trên DBMS.
Index dữ liệu on-chain để cung cấp dữ liệu tổng hợp cho người dùng.
Xây dựng công cụ phân tích dữ liệu on-chain.

### Benefit 
Có cơ hội để được học tập làm việc với các hệ thống và ứng dụng xây dựng trên blockchain.
Có thể học hỏi kinh nghiệm xây dựng một dự án trên blockchain từ đầu.
Lương thưởng cạnh tranh 1.500$ ~ 3.000$
Có thể làm việc remote.
Tuần làm việc 5 ngày + 1 ngày tự học theo team (Tham gia các buổi tự học, training, lighting talk)...

### Contact

Email: linhtt@skyline-vietnam.com/ Phone: 0375161163

**Comment by fuatto** [comment]
@Linh0401 phiền bạn sửa lại title và nội dung cho đúng format nhé, để lên được web golang.org.vn
