### ISSUE TITLE
HCM - APOLLO SOLUTIONS - GOLANG DEVELOPER - FULL TIME

### ISSUE THREAD

**Issue by Huyenmin2306** [golang-vietnam/job_board#119]
## Location

* Saigon, Vietnam

## Salary Expectation

* $700- 1300$/month

## Requirements
* Ít nhất 2 năm kinh nghiệm phát triển phần mềm chuyên nghiệp.
* Có kinh nghiệm về Git, Golang, Restful.
* Có kinh nghiệm tốt về thiết kế và phát triển ứng dụng hướng đối tượng.
* Có kiến thức tốt về Unit test, cơ sở dữ liệu.
* Có kinh nghiệm về SSL / HTTPS / Bash script, Unix, JWT, OAuth là một điểm cộng.
* Linh hoạt để tìm hiểu các công nghệ khác nhau và cởi mở trong làm việc về thiết lập thông số cấu hình, tích hợp.
* Hiểu biết vững về vòng đời phát triển phần mềm (SDLC), là một quy trình tiêu chuẩn để thiết kế ứng dụng.

### Responsibilities

Phân tích, thiết kế, phát triển và thử nghiệm các tính năng của sản phẩm phần mềm.
▪ Triển khai các tính năng từ thông số kỹ thuật thiết kế và cung cấp mã nguồn
(code) với chất lượng cao.
▪ Thực hiện kiểm tra chéo mã nguồn (code review), tối ưu mã nguồn (code
refactor).
▪ Đảm bảo các thành phần và ứng dụng tổng thể có hiệu năng tốt và dễ bảo
trì.
▪ Phối hợp với các thành viên khác trong nhóm để đảm bảo chất lượng và thời
gian phân phối triển khai sản phẩm được liên tục.
▪ Khám phá các công nghệ mới để giải quyết các thách thức kỹ thuật.
▪ Đưa ra giải pháp kỹ thuật cho vấn đề cụ thể và thực hiện giải pháp.
▪ Góp phần cải thiện nền tảng sản phẩm.
▪ Đưa ra các khuyến nghị để cải tiến liên tục.
Công nghệ sử dụng
▪ Golang
▪ MySQL, ElasticSearch
▪ Kubernetes

### Benefit
* Mức lương: $700 - $1300
* Chế độ đãi ngộ khác:
* Gói bảo hiểm chăm sóc sức khỏe toàn diện.
* Hỗ trợ ăn sáng, ăn trưa tại công ty.
* Reviews lương 02 lần/ năm.
* Các chế độ bonus ngày lễ, tết, du lịch

### Contact
Email: Ntkhuyen2306@gmail.com / Zalo/Phone: 0859773996

**Comment by fuatto** [comment]
@Huyenmin2306 phiền bạn sửa lại nội dung và title cho đúng format để lên được web golang.org.vn nhé
