### ISSUE TITLE
💥[Savvycom - Hà Nội] - Tuyển Golang Developer - All level - UP TO 2500$ - Sign bonus 01 tháng lương - PV online 💥

### ISSUE THREAD

**Issue by Trin96** [golang-vietnam/job_board#120]
## Location

* Tôn Thất Thuyết, Dịch Vọng Hậu, Cầu Giấy, Hà Nội, Việt Nam
* Thời gian làm việc linh hoạt

## Salary Expectation

* 700$ - 2500$ per month
* Sign bonus 01 tháng lương
* Nhận 100% lương trong giai đoạn thử việc

## Requirements
* At least 1.5 years of experience in web development, plus experience with Golang
* Comfortable writing HTML and HTML5, CSS, and Javascript.
* Good programming skills with PHP, Java or other Object-oriented programming languages.
* Experience with mobile web development.
* Good written and reading skills in English.
* Capable of problem analysis, design, and unit testing.
* Able to quickly learn new technologies.

## Responsibilities
* Be involved in Web (Golang/Python/NodeJS/PHP ...) Application Development projects.
* Working in cooperation with other project team members under the coordination of the Project Manager and having direct contact with foreign clients from US, EU, Australia and Singapore.
### Benefit
* Negotiable salary based on candidates' competence.
* Salary review twice a year.
* Monthly allowance from 1 Million - 1.5 Millions if certified English is satisfactory.
* In addition, 12 days annual leave, leave of one day in the month of the birthday.
* Receive social insurance according to Vietnamese Government regulations.
* Working in a young and professional environment. Direct contact with English-speaking foreign clients.
* Friendly & Open working environment (daily tea break, weekly sports time, monthly outdoor activity, annual holiday).
* Support English courses, sport activities & other team building activities.
* Obtain guidance and awareness of advanced technologies.
* Receive overtime-working allowance.
* Working hours: 5 days/week (Monday to Friday).
### Contact
Website: https://savvycomsoftware.com/
Email: job@savvycomsoftware.com

**Comment by fuatto** [comment]
@Trin96 Phiền bạn sửa lại nội dung và title cho đúng format để lên được web golang.org.vn nhé
