### ISSUE TITLE
[Trung Kính-HN] HBLAB tìm kiếm Junior/Middle Golang - Offer up to $1500

### ISSUE THREAD

**Issue by Giiang** [golang-vietnam/job_board#121]
### **Giới thiệu chung**
HBLAB có hơn 6 năm hoạt động trong lĩnh vực CNTT & IT Outsourcing. Xác định cho mình thế mạnh về Web & App, AI, HBLAB đã và đang liên tục nghiên cứu, phát triển, đặt mục tiêu đạt quy mô nhân sự 1.000 người vào năm 2024, cung cấp giải pháp chuyển đổi số chất lượng cho khách hàng. HBLAB xác định sứ mệnh của mình là theo đuổi hạnh phúc cho toàn thể nhân viên, hướng tới tầm nhìn nâng tầm chất lượng Việt Nam. Trong quá trình này, HBLAB chào đón các bạn tham gia vào đội ngũ nhân sự tài năng & nhiều hoài bão của chúng tôi để cùng nhau học hỏi, phát triển và thành công.

### **Mô tả công việc**
Với sứ mệnh “Theo đuổi hạnh phúc cho toàn thể nhân viên, mang đến dịch vụ tốt nhất cho khách hàng. Nâng tầm chất lượng Việt”, HBLAB không ngừng tìm kiếm những người bạn đồng hành, có thể làm việc, gắn bó lâu dài, góp phần vào sự phát triển của công ty, và cũng kỳ vọng bạn sẽ trở thành những thành viên trụ cột của công ty trong tương lai. Đồng hành cùng HBLAB tại vị trí này, bạn sẽ:
– Sử dụng Golang để tham gia phát triển các ứng dụng cho khách hàng Nhật Bản, duy trì và nâng cấp các tính năng của sản phẩm
– Tư vấn giải pháp, thiết kế, xây dựng tạo ra các sản phẩm phần mềm tối ưu, phù hợp với nhu cầu của khách hàng.
– Nghiên cứu và áp dụng công nghệ, kiến trúc service mới tại các dự án lớn phù hợp với định hướng và chiến lược phát triển của Công ty.
Chúng tôi tin rằng với cơ hội – thách thức ở HBLAB, chúng ta có thể đồng hành cùng nhau và cùng chia sẻ thành công ở chặng đường phía trước.

### **Yêu cầu công việc**
– Có tối thiểu 2 năm kinh nghiệm lập trình và thành thạo một trong các ngôn ngữ: Golang, Java, PHP, Python, Node.js… Ưu tiên các bạn đã có kinh nghiệm về Golang
– Có kinh nghiệm làm việc với các hệ quản trị cơ sở dữ liệu như MySQL, PostgreSQL,…
– Có kinh nghiệm về unit test
– Sử dụng thành thạo Git và gitflow
– Kỹ năng phân tích và giải quyết vấn đề
– Kỹ năng giao tiếp tốt, tinh thần trách nhiệm và tỉ mỉ trong công việc

### **Vì sao bạn yêu thích làm việc tại HBLAB**
– Làm việc cùng những đồng nghiệp trẻ tài năng, đầy đam mê và nhiệt huyết.
– Môi trường thoải mái, năng động, chuyên nghiệp
– Lãnh đạo quan tâm mọi mặt tới nhân viên
– Được tư vấn và định hướng về career-path rõ ràng.
– Được chăm lo đào tạo kỹ năng mềm, các kỹ năng quản lý dự án, quản lý chất lượng.
– Cơ hội tiếp cận và nắm bắt các xu hướng công nghệ (AI, IoT, VR, AR …).

### **Quyền lợi chung**
– Offer up to $1500
– Fix 13 tháng lương
– Thưởng performance trung bình 2 tháng lương/năm (giải ngân thưởng 2 lần trong năm)
– Review lương 2 lần/năm: tháng 4 và tháng 10
– Teambuilding 250.000 VND/người/tháng
– Beauty care: 200.000 VND/người/tháng cho nhân viên nữ
– Quỹ đào tạo: 3.000.000 VND/người/năm
– Trợ cấp tiếng Nhật
– Thưởng chứng chỉ
– Bảo hiểm sức khỏe PVI cho nhân viên từ 1 năm thâm niên
– 12 ngày phép/năm, BHXH/YT/TN đầy đủ theo quy định của Luật Lao động
– Nghỉ lễ Tết theo quy định của Nhà nước và kèm theo thưởng cho các ngày lễ lớn trong năm: 30/4 1/5, 2/9, tết,…
– Thời gian làm việc: thứ 2 – thứ 6: 8h-17h30 (nghỉ thứ 7, chủ nhật)

### Liên hệ
Vui lòng liên hệ giangph@hblab.vn hoặc giangph_3 (skype) để được tư vấn, hỗ trợ về công việc

**Comment by fuatto** [comment]
@Giiang phiền bạn sửa lại nội dung và title cho đúng format để lên được web nhé
