### ISSUE TITLE
[HN_Zinza] Tuyển dụng Golang Developer từ 6 tháng kinh nghiệm (10M-20M)

### ISSUE THREAD

**Issue by GiangNXT** [golang-vietnam/job_board#123]
###  Mô tả công việc

Tham gia vào dự án phát giám sát xe thông qua thiết bị thông minh được gắn trên các xe của hệ thống
Hệ thống giám vị trí realtime của ~40k xe tại 1 thời điểm. Vẽ lại cung đường của xe đã đi
Database quản lý hàng tỷ record

 **Công nghệ sử dụng trong dự án**

Docker, docker-compose
Kubernetes, Ansible
Vsphere client để tạo máy ảo cho hệ thống
Database: MongoDB (sharding cluster) , mysql cluster,postgresql-ha cluster (sử dụng patroni để manage)
Redis
Message Queue: Kafka, MQTT Broker (clustering)

### Yêu cầu công việc

Có tư duy logic tốt
Có 6 tháng-1 năm kinh nghiệm với một trong những ngôn ngữ sau: Golang, Nestjs, Nodejs
Có kinh nghiệm làm việc trên các database: MongoDB hoặc mysql
Có kinh nghiệm làm việc với redis
Có kinh nghiệm làm việc với REST Api

 **Điểm cộng**

Có kinh nghiệm làm việc với CI/CD
Có khả năng dựng server, môi trường phát triển dự án
Có khả năng đọc hiểu thiết kế hệ thống, thiết kế chi tiết
Có kinh nghiệm làm việc theo process Agile / Scrum
Tiếng anh giao tiếp tốt

###  Quyền lợi

Chế độ nhân sự dành cho nhân viên chính thức trong công ty ZinZa Technology hiện tại như sau:

Công ty cung cấp thiết bị làm việc cho toàn bộ nhân viên chính thức
Join vào dự án ODC. Khi join dự án bắt đầu từ tháng thứ 4 trở lên:
Trợ cấp ODC (team leader): 1M/tháng.
Trợ cấp ODC (member): 700k/tháng
Trợ cấp tiếng Nhật, và các chứng chỉ IT liên quan (hình thức: trợ cấp hàng tháng, tăng lương…)
Thưởng thâm niên cho các nhân sự làm việc tại công ty từ 2 năm trở lên. Mức thưởng cụ thể như sau:
Nhân viên có 2 năm thâm niên làm việc tại công ty: 2,000,000vnd
Nhân viên có 3 năm thâm niên làm việc tại công ty: 4,000,000vnd
Nhân viên có 4 năm thâm niên làm việc tại công ty: 6,000,000vnd
Nhân viên có từ 5 năm thâm niên làm việc tại công ty: 10,000,000vnd
Được tham gia các Câu lạc bộ dưới sự tài trợ chính thức của Công ty: CLB Bóng đá, Cầu lông, các CLB Game, tham gia các bữa tiệc sinh nhật, team building hàng quý, hoạt động ngoại khóa của công ty …
Có cơ hội được onsite tại thị trường Nhật Bản.
Thời gian làm việc: từ thứ 2 đến thứ 6 từ 8h30 – 17h30 (Nghỉ thứ 7, CN). Thời gian làm việc thoải mái, không gò bó.
Môi trường làm việc chuyên nghiệp, cởi mở, thân thiện
Xét tăng lương theo năng lực và kết quả công việc: 2 lần/năm (T6 và T12)
Lương tháng 13
Cơ hội thăng tiến cao trong môi trường tăng trưởng liên tục
Du lịch 2 lần/năm
Chi tiết các chế độ khác và các mức trợ cấp chứng chỉ: https://bom.to/5vnZNw

### Contact
Email: giangnt1@zinza.com
hoặc fb giang nguyễn: https://www.facebook.com/Giangnguyenhr206/ để trao đổi thêm thông tin và ứng tuyển

**Comment by fuatto** [comment]
@GiangNXT phiền bạn sửa lại nội dung và title đúng format để lên được web nhé
