### ISSUE TITLE
Koina.VN - Software Engineer (Golang) - HCMC - FT

### ISSUE THREAD

**Issue by vinhdevie** [golang-vietnam/job_board#129]
## Location

* K-GROUP Building, 12B Đ. Nguyễn Hữu Cảnh, Phường 19, Bình Thạnh, Thành phố Hồ Chí Minh, Vietnam [(Google Maps)](https://goo.gl/maps/Po1Em5WEavzg7H3V9)
* Fulltime

## Salary Expectation

* $800~$2000/range

## Requirements
* 1+ years Software Engineering experience
* Knowledge and experience in Golang or any general purpose programming languages including but not limited to: C/C++, Python, Java, Javascript ES6. and be willing to change to Golang.
* Excellent attention to details.
* Self-motivated to explore new technologies, applications, and environments.
* Careful, detail and high responsibility
* Open mind and be willing to learning new thing

### Must Have

* Golang or willing to change to Golang

### You’ll be responsible for

* As Backend Developer you will be involved in the planning, development, and maintenance of the web & mobile app supporting our products and services, have the chance to make leading enterprise product for massive user in Vietnam market.
* Optimizing components for consistency and performance across desktops, tablets, and mobiles.
* Collaborate with cross-functional teams to design, develop and ship new features.
* Optimize the system for reliability and performance.
* Fix bugs and improve the system.
* Contribute knowledge to the technical team.

### You can bring

* Your good attitude
* Your curiosity
* Your 🧠

### Why it would be awesome to work with us
* A strong and friendly team, who will support you when needed, and troll you when bored
* A culture that encourage you to speak your mind and take ownership to the product that you made
* You can learn about not only technology but also business

### Contact

Email: vinh.nguyen@koina.vn
Mobile: 0984872865

**Comment by vibros68** [comment]
I have about 4 years experient of Golang. Is that okay if I join your team?

**Comment by vinhdevie** [comment]
> I have about 4 years experient of Golang. Is that okay if I join your team?

@vibros68 sure, the position is open to anyone who have at least 1 year experience.
