### ISSUE TITLE
Grab - Software Engineer, Frontend - HCMC - Fulltime

### ISSUE THREAD

**Issue by hongngocanhthu** [golang-vietnam/job_board#15]
## Location
* MapleTree, 1060 Nguyen Van Linh Str., District 7, Saigon
* Fulltime
* Grab is more than just the leading ride-hailing and mobile payments app in Southeast Asia. We use data and technology to improve everything from transportation to payments and logistics across a region of more than 620 million people. Working with governments, drivers, passengers, and charities, we aim to unlock the true potential of the region by solving problems that hinder progress.
*Grab began as a taxi-hailing app in 2012, but has extended its product platform to include private car services (GrabCar & GrabShare), motorcycle taxis (GrabBike), social carpooling (GrabHitch) and last mile delivery (GrabExpress). We are focused on pioneering new commuting alternatives for drivers and passengers with an emphasis on speed, safety, and reliability. Currently we offer services in Singapore, Indonesia, Philippines, Malaysia, Thailand and Vietnam; however, we also have R&D offices in Bangalore, Beijing, & Seattle

## Requirements
* Basic understanding of User Experience
* Strong understanding of Javascript/React, Webpack
* Experience in writing unit test/integration test
* Strong knowledge on layouting and crafting easy to maintain layouts that scale to any screen size

## Responsibilities
* Define and shape the fundamentals of engineering at Grab.
* Design and write maintainable code at scale
* Discuss/propose solution to improve User Experience
* Continuously discuss, debate with other team members to propose optimal solutions for different problems

### The day-to-day activities
* Build and deploy performant modern web applications in React, Redux, Webpack, Typescript, Graphql
* Convert from design/prototype to responsive interface on the web
* Work with product managers, data analysts and UI designers to implement products and features, and test their impact to business metrics.
* Participate in code and design reviews to maintain our high development standards
* Engage in service capacity and demand planning, software performance analysis, tuning and optimization
* Collaborate with product and experience teams to define and prototype feature specifications
* Design, build, analyze and fix large-scale systems
* Learn full stack performance tuning and optimization
* Debug and modify complex, production software

### Why it would be awesome to work with us
* Positive & Collaborative environment
Grabbers thrive in a corporate culture that values every team member's contribution towards our goal of improving lives.

* Rocket fuel for careers
Grabbers experience hyper professional growth and all the challenges that entails. Grow your skills while working to solve real issues across the region.

* Fun & dedicated family
Grabbers work hard and play hard. Our teams grow as one as they overcome challenges and have fun along the way.

* Some of benefits are:
Macbook is provided.
Extra Medical Insurance.
14 days annual leaves, working Monday - Friday.
Free drive with Grab (budget follow your level)

### Contact
Hong Ngoc Anh Thu - Talent Acquisition Business Partner
Email: thu.hong@grabtaxi.com
Skype: hongngocanhthu

**Comment by fuatto** [comment]
Lapsed!
