### ISSUE TITLE
Grab - Engineering Manager - HCMC - Fulltime

### ISSUE THREAD

**Issue by hongngocanhthu** [golang-vietnam/job_board#16]
## Location
* MapleTree, 1060 Nguyen Van Linh Str., District 7, Saigon
* Fulltime
* Grab is more than just the leading ride-hailing and mobile payments app in Southeast Asia. We use data and technology to improve everything from transportation to payments and logistics across a region of more than 620 million people. Working with governments, drivers, passengers, and charities, we aim to unlock the true potential of the region by solving problems that hinder progress.
Grab began as a taxi-hailing app in 2012, but has extended its product platform to include private car services (GrabCar & GrabShare), motorcycle taxis (GrabBike), social carpooling (GrabHitch) and last mile delivery (GrabExpress). We are focused on pioneering new commuting alternatives for drivers and passengers with an emphasis on speed, safety, and reliability. Currently we offer services in Singapore, Indonesia, Philippines, Malaysia, Thailand and Vietnam; however, we also have R&D offices in Bangalore, Beijing, & Seattle

## Requirements
* 7 ~ 12 years software development management experience, preferably in delivering B2C products/services/content.
* BS/MS in Computer Science or other related Degrees.
* Significant experience as a successful software development leader in large scale, highly available Internet and mobile applications.
* Experience in building and growing a highly productive software engineering team.
* Proven ability to make smart feature versus time-to-market trade-offs; experience using data and metrics to back up assertions of business value.

## Responsibilities
Build and lead a highly productive team of software engineers. Deep, hands-on programming and technical design skills with demonstrated willingness and capability to learn new technologies quickly.
* Demonstrated ability to design, build, and deliver complex, successful engineering systems or products efficiently and with high quality.
* Proven team leadership, interpersonal skills, and ability to get things done.
* Ability to clearly communicate high level strategy and technical details effectively across disciplines, locations, and organizations, including to senior leadership.
* Strong bias for action; ability to juggle multiple priorities and build a sense of urgency in a dynamic environment.

### The day-to-day activities
* Collaborate with the product, business, design and data team to be on top of your deliverable.
* As part of growth leadership team, contribute to and lead the direction of the growth team.
* Timely delivery of highly reliable and scalable engineering architecture, and high quality, maintainable and operationally excellent code.
* Timely closure of all the assigned code review and design reviews.
* Recruit, interview and close top talents.
* Mentor and coach engineers in the team.

### Why it would be awesome to work with us
* Positive & Collaborative environment
Grabbers thrive in a corporate culture that values every team member's contribution towards our goal of improving lives.

* Rocket fuel for careers
Grabbers experience hyper professional growth and all the challenges that entails. Grow your skills while working to solve real issues across the region.

* Fun & dedicated family
Grabbers work hard and play hard. Our teams grow as one as they overcome challenges and have fun along the way.

* Some of benefits are:
Macbook is provided.
Extra Medical Insurance.
14 days annual leaves, working Monday - Friday.
Free drive with Grab (budget follow your level)
### Contact
Hong Ngoc Anh Thu - Talent Acquisition Business Partner
Email: thu.hong@grabtaxi.com
Skype: hongngocanhthu

**Comment by fuatto** [comment]
Lapsed!
