### ISSUE TITLE
[Kubtech] Senior Backend Engineer and Smart Contract Engineer, Tan Binh, HCM FT

### ISSUE THREAD

**Issue by khoanhd** [golang-vietnam/job_board#168]
## Location

* Saigon, Vietnam
* Onsite

## Salary Expectation

* 1500$ - 3000$

## Requirements
* Golang
* NodeJS
* PostgreSQL
* 3+ years Software Engineering experience

### Must Have

* Can design software architecture of a product/project specification.
* Experience in Software Development Life Cycle. 
* 3+ YOE as Backend Engineer.
* Can deal with any programming languages (Golang, NodeJS, Python, PHP,...).
* Can do in K8S, Docker.
* Can do in Queue, Kafka.
* Can do database design & database indexing.
* Experience in Backend ecosystem (API, Database, Caching, Cloud, CI-CD, Microservices, Docker).
* Can build API with Restful Standard and JWT/OAuth2 authentication.
* Git version control.
* Can detect & prevent software security issues.
* Can do application tuning: caching, queue, database, code logic...
* Can troubleshoot any stacks of Application.
* Can detect & prevent system security protection.
* Can do DevOps domain.
* Problem solving skills.
* Self-motivated, ability to work independently.
* Ability to write unit tests, functional tests.

### Ideally
* Ability to write TDD.

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Design & Tuning Database.
* Design & implement component interactions.
* Develop API for partner & Frontend (NodeJS, Golang,  Restful API,...).
* Develop interconnect with Queue, Kafka.
* Optimizing server-side performance, ensure api response <= 100ms.
* Collaborate with DevOps on CI-CD, System Architect, Monitoring.
* Collaborate with Frontend to have a prototype before implementation.
* Collaborate with QC to have scenarios based on user stories.
* Communicate with Frontend and support API Mock.
* Participate in code review.

### Why it would be awesome to work with us
* Be the change: Shoot to the top with a high-octane, innovative SaaS company.
* Professional development: Upgrade your skills and ignite your career.
* Collaborative atmosphere: At Kubtech everyone works together to execute the mission.
* Excellent benefits: We offer competitive compensation packages.  
* Team spirit: Caring for our people and bonding together are musts for us.
* Dynamic growth: Our teams are scaling up quickly as the recruiting market is booming. There’s no better time than now to come on board!
* Kubtech has a diverse, international, and supportive community culture. You’ll collaborate with coworkers and clients across US, Canada, Singapore, Malaysia, Bangladesh… Our English-speaking environment lets you improve your language skills.

### Interesting engineering projects
* Blockchain

### Contact
Email: nhung.phan@kubtech.net

**Comment by GaryHuu** [comment]
xa`m

**Comment by GaryHuu** [comment]
mồm nói hay lắm Kh* CTO
