### ISSUE TITLE
Grab - Software Engineer, Fullstack - HCMC - Fulltime

### ISSUE THREAD

**Issue by hongngocanhthu** [golang-vietnam/job_board#17]
## Location

* MapleTree, 1060 Nguyen Van Linh Str., District 7, Saigon
* Fulltime
* Grab is more than just the leading ride-hailing and mobile payments app in Southeast Asia. We use data and technology to improve everything from transportation to payments and logistics across a region of more than 620 million people. Working with governments, drivers, passengers, and charities, we aim to unlock the true potential of the region by solving problems that hinder progress.
Grab began as a taxi-hailing app in 2012, but has extended its product platform to include private car services (GrabCar & GrabShare), motorcycle taxis (GrabBike), social carpooling (GrabHitch) and last mile delivery (GrabExpress). We are focused on pioneering new commuting alternatives for drivers and passengers with an emphasis on speed, safety, and reliability. Currently we offer services in Singapore, Indonesia, Philippines, Malaysia, Thailand and Vietnam; however, we also have R&D offices in Bangalore, Beijing, & Seattle

### The must haves
* Strong CS fundamentals (with competencies in algorithms and data structures)
* Proficient understanding of the HTTP protocol
* Experience in shipping web applications to production, CI/CD flow
* Familiarity with the whole web stack, web protocols, and web performance optimization techniques
* In-depth understanding of web frameworks (willing to receive application with diversified programing languages)
* Detailed knowledge of minimum one modern JavaScript framework: React, Ember, Angular, etc

### Nice-to-haves
* Experience with Go/Ruby
* Experience with ES6/ES2015 or ES7/ES2016
* Experience with React, Redux/Typescript
* Experience with at least one CSS preprocessor: Sass, Less, PostCSS, Stylus, etc

## Responsibilities
* Design, implement & manage web apps that impact millions of users
* Experience a shipping culture that uses the state of the art web technologies
* Grow in an environment passionate about knowledge-sharing and code review
* Learn software engineering practices for coding at scale: static analysis, feature flags, instrumentation, and more

### The day-to-day activities
* Design and implement RESTful APIs (Golang, Java)
* Build and deploy performant modern web applications in React, Redux, Webpack, ES6, Flow and Typescript
* Architect efficient and scalable backend systems
* Write unit, functional and end-to-end tests
* Write high-quality code (Golang, Java) that communicates with upstream backend services via HTTP APIs, gRPC, graphql
* Identify and resolve performance and scalability issues
* Participate in code reviews

## Why you should join Grab
* Have a chance to design, implement & manage web apps that impact millions of users
* Have a change to work with one of the biggest system in South-east-asia with huge amount of data
* Experienced a shipping culture that uses the state of the art web technologies
* Grow in an environment passionate about knowledge-sharing and code review
* Learn software engineering practices for coding at scale: static analysis, feature flags, instrumentation, and more

Notes: for this position, we’re opening for all Fresher/Junior and Senior positions.

### Why it would be awesome to work with us
* Positive & Collaborative environment
Grabbers thrive in a corporate culture that values every team member's contribution towards our goal of improving lives.

* Rocket fuel for careers
Grabbers experience hyper professional growth and all the challenges that entails. Grow your skills while working to solve real issues across the region.

* Fun & dedicated family
Grabbers work hard and play hard. Our teams grow as one as they overcome challenges and have fun along the way.

* Some of benefits are:
Macbook is provided.
Extra Medical Insurance.
14 days annual leaves, working Monday - Friday.
Free drive with Grab (budget follow your level)
### Contact
Hong Ngoc Anh Thu - Talent Acquisition Business Partner
Email: thu.hong@grabtaxi.com
Skype: hongngocanhthu

**Comment by fuatto** [comment]
Lapsed!
