### ISSUE TITLE
SoBanHang - Golang Developer - Saigon - FT

### ISSUE THREAD

**Issue by trantuthien** [golang-vietnam/job_board#176]
## Location

* Saigon, Vietnam

## Salary Expectation

* $1.000 - $3.500

## What you need to have
* 1-4 years of experience developing micro-services applications in Go Lang, Python
* Familiar with cloud infrastructure environments, especially AWS/GCP
* Experience in containerization technologies such as Docker, Kubernetes.
* Experience in REST, and Message Broker.
* Familiar with PostgresSQL/ MySQL.
* Experience with Elastic, Redis, Socket and Cloud Infrastructure.

### Ideally

* Proactive and effective self-learning skills and research.
* Open-minded and keen to learn new thing.
* Self-motivated with a positive “can-do” attitude and teamwork.
* Well-disciplined, and responsible for the delivery of task.
* Preferably to be able to communicate in English.
* Experience with multi DB (SQL, NoSQL…) is a plus.

### Responsibilities

Great power comes with great responsibilities!
Build SoBanHang with us :v 

### Contact

Homepage: sobanhang.com
Email to Techteam: thien.tran@sobanhang.com / fb: trantu.thien

**Comment by trantuthien** [comment]
@fuatto ơi, pls check
many thanks

**Comment by thanhdinh98** [comment]
Hi @trantuthien, 
Thanks for posting the job.
I wonder if the job is currently opening at this moment?
