### ISSUE TITLE
Exgo - Senior Software Engineer - Saigon - FT

### ISSUE THREAD

**Issue by Nguyen-Nguyen-Quynh-Huong** [golang-vietnam/job_board#19]
## Location

* Dist. 2, Saigon, Vietnam

## Salary Expectation

* $2000/month 

## Requirements

* Experienced in using GoLang or Experienced in using C++/Python/Java and willing to switch to GoLang.

### Must Have

* Solid knowledge in web development.
* Experience with RESTFul APIs.
* Experience with PostgreSQL.
* Experience working on Linux, Git, Nginx.
* Experience working on Redis/Memcached for caching/speeding up apps performance.
* Identify and resolve performance and scalability issues.
* Motivation to learn a new programming language.

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Building an application to connect and support freight transportation processes. Our tech team work really hard try to build an application that solve most difficulties any Shippers, Carriers and Drivers meet.

### Nice to have:

* Basic Understanding of Echo framework.
* Basic Understanding of gRPC.
* Experience working on ElasticSearch.
* Experience working on microservice based architecture and design, scale systems using RabbitMQ/Kafka is a plus.
* Experience with high performance websites catering to millions of daily traffic is a plus.

## Contact

* Email: huongngng96@gmail.com 
* Phone: 0776717990
* Skype: huongngng96

**Comment by fuatto** [comment]
Lapsed!
