### ISSUE TITLE
VNG - Senior Software Engineer (Golang) - HCM - FT

### ISSUE THREAD

**Issue by Nguyen-Nguyen-Quynh-Huong** [golang-vietnam/job_board#21]
## Location

* Saigon, Vietnam

## Salary Expectation

* Negotiate

## Requirements
* Golang
* Redis, Memcache...
* MySQL, PostgreSQL, ...
* 3+ years Software Engineering experience

### Responsibilities

*Great power comes with great responsibilities!

### You’ll be responsible for

* Building ZaloPay - a mobile payment application with many unique features

### Contact
* Skype: huongngng96
* Mail: huongnnq@vng.com.vn
![13925835_1106215049445501_7122732178064345412_o](https://user-images.githubusercontent.com/52448078/62674746-f9afe800-b9cd-11e9-953d-38caefecc0ef.png)

**Comment by fuatto** [comment]
Lapsed!
