### ISSUE TITLE
Nextop - Back-End Developer (Golang) -  HN - FT

### ISSUE THREAD

**Issue by huynguyen-11** [golang-vietnam/job_board#22]
## Location

* 12Floor, Keangnam Landmark Tower, E6, Me Tri, Quan Tu Liem, Ha Noi

## Salary Expectation

* Up to $1,500

## Requirements
* Golang
* 1 - 2 years as developers

### Must Have

* Extensive experience in general purpose programming language. 
* Experience working with distributed and parallel systems and backend applications. 
* Practical experience with Design Patterns, Software Architecture. 
* Extensive experience with Go 
* Good knowledge of relational databases and/or NoSQL 
* Extensive experience in blockchain 
* Experience with scripting with Bash, ZSH, etc. 
* A solid understanding of Linux development 

### You’ll be responsible for

* Microservice architecture. 
* Redis, Blockchain, SQL and key-value storage, Message queue 
* Cloud-based infrastructure following 12 factors using Docker. 
* Go as main language 

### Why it would be awesome to work with us

*Salary: Competitive with lucrative add-ons (based on skills and experience)
* Bonus : Twice a year (equivalent to 2 months salary). Salary Review: 2 times/year based on employee's performance and contribution
* Well-equipped with insurance package as stated by Labor code
* Other benefits as per stated in Vietnamese Labor Law
* Working hours: 9:00 ~ 17:00 (5 days per week)

### Contact
Apply your CV via Email: quochuy111nguyen@gmail.com
Subjects: Back-end (Golang) - Tên bạn

**Comment by fuatto** [comment]
Lapsed!
