### ISSUE TITLE
BStar Solutions - Go Developer - HCMC - FT

### ISSUE THREAD

**Issue by circlehuy** [golang-vietnam/job_board#23]
## Location
* Saigon, Vietnam or Thailand

## Salary Expectation
* 17.000.000 ~ 30.000.000 VND (NET) / month

## Requirements
- 3 years experienced engineer who has at least 6 months working on GO project
- Knowledge of Go programming language, paradigms, constructs, and idioms
- Knowledge of common Goroutine and channel patterns
- Experience with the full site of Go frameworks and tools, including:
*Dependency management tools such as Godep, Sltr, etc.
*Go’s templating language
*Go’s code generation tools, such as Stringer
*Popular Go web frameworks, such as Revel
*Router packages, such as Gorilla Mux
- Ability to write clean and effective Godoc comments
- Good knowledge of OOP, Design Pattern, Data Structure and Algorithm
- Experience with SQL, NoSQL, MongoDB
- Self-motivated to explore new technologies and environments
- Familiar with Git/Jira

### Responsibilities
- Work with technical architect on the project's architect design
- Work as a key developer to develop Go packages and programs that are scalable and maintainable
- Report to project leader or manager.
- Estimate your tasks
- Coordinate with the rest of the team working on different layers of the infrastructure

### Why it would be awesome to work with us
- Very attractive salary
- Full salary during probation period 
- Chances to work directly with many customers all over the world
- Company budget for team building and sports activities.
- Company budget for Happy hours

### Contact
*Skype: circlehuy
*Email: huy.vong@glints.com
*Zalo/Whatsapp: 0906338878

[Golang Developers - BStar Solutions.pdf](https://github.com/golang-vietnam/jobs/files/3792924/Golang.Developers.-.BStar.Solutions.pdf)

**Comment by fuatto** [comment]
Lapsed!
