### ISSUE TITLE
Bocasay Vietnam - Golang Team Lead - Hanoi - FT

### ISSUE THREAD

**Issue by brandonlu1204** [golang-vietnam/job_board#24]
## Location

* 107 DETECH TOWER II, Nguyen Phong Sac, Dich Vong Hau, Cau Giay, Hanoi

## Salary Range

* Up to $2,500 gross

## Your Responsibilities

* Develop the back-end system of an IT Infrastructure Monitoring Tools
* Preventive and corrective maintenance of the product (support level 3)
* Skills transfers made in internal team
* Participating in the development of specification techniques
* Load estimation of product evolution
* Write and execute the unit and functional test
* Delivery and integration of the product

### Must Have

* Expert in development using Golang/Python (min 4 years of experience)
* Hands-on experience with Object-Oriented programming
* Experience in design and implementation of REST APIs
* Familiar with Linux distribution: Debian (8 or 9), Ubuntu 16.04, CentOS 7
* Skilled at GIT

### Nice to have

* Familiar with Behaviour Driven Development (BDD)
* Experience in MongoDB and Redis
* Experience in RabbitMQ, influxDB, Docker, Ansible
* Experience in a SCRUM environment
* Experience with JS framework  (/React/Vue/ Ember)

### Why it would be awesome to work with us

* We are committed to maintaining a high level of satisfaction among our employees
* Exceptional talents will be matched with an exceptional salary
* Encourage people to be lead & push new ideas forward in our small teams
* Training & study sponsorship
* Tons of fun & exciting team activities: annual company trip, monthly BBQ night, happy hours, etc. And much more...!

### Contact

Homepage: https://www.bocasay.com/boost-your-career-and-take-part-in-a-success-story
Mr. Thanh: tlu@bocasay.com
Mobile: 0972 960 294
Skype: thanhlu0494

**Comment by fuatto** [comment]
Lapsed!
