### ISSUE TITLE
JRB - GOLANG DEV - REMOTE/HO CHI MINH - PT

### ISSUE THREAD

**Issue by trantuthien** [golang-vietnam/job_board#25]
## Location

* Saigon, Vietnam
* Remote

## Salary Expectation

* $9/HOUR or range

## Requirements
* Show us your project
* 0.5+ years Software Engineering experience

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Building a new e-com

### Contact
fb: trantu_thien

**Comment by leowilbur** [comment]
fb address is not exist ==!

**Comment by fuatto** [comment]
Lapsed!
