### ISSUE TITLE
Stably - Fullstack Engineer - HCMC - Fulltime

### ISSUE THREAD

**Issue by Git-on-my-level** [golang-vietnam/job_board#26]
## About us
Stably is building financial products and infrastructure for a globally connected and decentralized world. By leveraging blockchain and stablecoin technologies, we provide access to robust financial infrastructure without the friction, cost and frustration of traditional financial systems. Learn more about us at www.stably.io.

## Why work at Stably?
We are changing the landscape of financial accessibility by creating products and infrastructure to empower users. We are democratizing access to financial services that used to be out of reach for many people, creating programmable money that anyone can build on top of, and creating infrastructure that allows money to be more frictionless and borderless. 

## How do you know if you're a good fit?
* You enjoy challenges and solving new problems
* You are a lifelong learner and enjoy picking up new skills
* You learn from those around you and help educate others
* You can not only code, but also communicate your ideas clearly
* You have some interest in finance, economics, or trading

## Must Have
* Golang experience or experience with a strongly typed language
* 2+ years backend or fullstack experience
* Good knowledge of computer science fundamentals
* Proficient in verbal and written English

## Nice to Have
* Familiarity with Python/Javascript/TypeScript
* Experience with ReactJS or other frontend frameworks
* Experience writing efficient and thoughtful SQL queries
* A technical understanding of blockchain
* Familiarity with event driven systems
* Practical cyber security knowledge
* Experience developing and deploying web applications in production
* Experience with DevOps and DevOps infrastructure

## Location

* Ho Chi Minh City, Vietnam

## Salary Expectation

* $1000-2500/month

### Contact

Email: careers@stably.io

**Comment by fuatto** [comment]
Lapsed!

**Comment by Git-on-my-level** [comment]
We are still hiring! 😄
