### ISSUE TITLE
JX - Golang dev - Remote/Saigon - PT

### ISSUE THREAD

**Issue by trantuthien** [golang-vietnam/job_board#31]
## Location

* Saigon, Vietnam
* Remote

## Salary Expectation

* rate by hour

## Requirements
* Golang
* Biết thêm ngôn ngữ nào nữa càng tốt

### Must Have

* chịu khó, chịu cày với anh em
* có trách nhiệm với task đã giao

### You’ll be responsible for

* làm dự án cùng nhau 

### Contact
* FB: http://facebook.com/trantu.thien

**Comment by fuatto** [comment]
@trantuthien , please note that all **MUST BE strictly** written in English!
