### ISSUE TITLE
JRB - Golang Developer - Saigon - FT

### ISSUE THREAD

**Issue by trantuthien** [golang-vietnam/job_board#39]
## Location

* Saigon, Vietnam

## Salary Expectation

* $/month or range

## Requirements
* Golang exps from 1 year

## Skills
* Experience with 
docker, micro service, grpc

### Responsibilities
Great power comes with great responsibilities!

### You’ll be responsible for
* Building a new service for E-com

### Why it would be awesome to work with us
teambuilding every day

### Contact

http://facebook.com/trantu.thien/

**Comment by fuatto** [comment]
@trantuthien anh ơi, em có truy cập thử info phần Contact nhưng không được, phiền anh kiểm tra/ cập nhật lại dùm em ạ. Cho em hỏi thêm là tên Công ty mình là JX thì em có search thử trên google không thấy, nếu được anh cho em xin thông tin của công ty mình được không?

**Comment by trantuthien** [comment]
> @trantuthien anh ơi, em có truy cập thử info phần Contact nhưng không được, phiền anh kiểm tra/ cập nhật lại dùm em ạ. Cho em hỏi thêm là tên Công ty mình là JX thì em có search thử trên google không thấy, nếu được anh cho em xin thông tin của công ty mình được không?

a liên hệ vs e qua email nhé

**Comment by trantuthien** [comment]
now is reopening
Wellcome all
