### ISSUE TITLE
Paditech - Senior Backend Developer (Golang) - Hanoi - FT

### ISSUE THREAD

**Issue by lananh96** [golang-vietnam/job_board#40]
## Location

* Hanoi, Vietnam
* Fulltime

## Salary Expectation

* Up to $2500, depends on experience and skill

## Requirements
* Strong knowledge of Golang
* Ability to design, build and optimise backend application for maximum speed, scalability and availability.
* Demonstrated experience in implementing highly scalable backend services.

### Must Have

* Experience working with Golang over 2+ years, experience with NodeJS is an advantage.
* Having good programming thinking, object oriented programming thinking, ability to
self-learn and learn new technologies on the web platform.
* Having skills in teamwork, working under pressure and high sense of responsibility.
* Good English, management experience.

### Responsibilities

* Building and developing Core and Blockchain products on the Cosmos Network (ATOM) platform for Japanese customers
* Participating in the development of payment services, giftcode, website system for mobile games, mobile apps, payment gateway and e-wallet
* Participate in requirements inquiry, analysis, design, and technology research when assigned
* Research and develop big data aggregation and analysis tools.

### Contact

Homepage: paditech.com
Email: anhdtl@paditech.com (mobile number optional)

**Comment by fuatto** [comment]
@lananh96, kiểm tra lại dùm anh tiêu đề nha, em xem phần ví dụ (copy rồi sửa tương ứng thông tin)
