### ISSUE TITLE
Backend Developer (Golang)

### ISSUE THREAD

**Issue by junnhk** [golang-vietnam/job_board#41]
## Location

* Saigon, Vietnam
* Fulltime

## Salary Expectation

* 30 - 70M VND/month

## Requirements
* 4+ years of product software development experience.  We also welcome strong candidate having fewer years of experience as  well, please tell us why "year" doesn't matter to you in the application  letter
* Solid technical skill, you talk in confident about Golang. Big plus if you can talk broader than that
* Knowledge about REST / gRPC API and databases as MongoDB, , Elasticsearch…
* Understanding of system design and tuning for high performance, scalability and reliability
* Experience with Microservice architect is a plus
* Experience with NATS architect is a plus
* Experience with Devops is a plus

## Skills
* Golang, mongoDB, REST/Microservices

### Must Have
* Understand the value of writing test
* Good English communication

### Ideally
* Understand the balance between technical and business decisions
* Open-minded, can-but-not-blindly-do attitude. You have "can-do" attitude, which is already very cool, but you also must be able to pause and ask "should we do it"
* Be on your own, dedicated and committed, we strongly believe in autonomous, there's likely no one to tell you what to do
* And be a TEAM PLAYER, because we can move nowhere without a team
* Must be able to say "I was wrong", because no one is perfect
* And last but not least we always treat people with respect

### Responsibilities
* Participate in all phases of the development life-cycle
* Optimize the system for reliability and performance
* Write high-quality, clean, elegant, and maintainable code
* Understand  the product thoroughly, constantly optimize the product, identify and  fix problems, improve stability and user experience
* Analyze requirements, design and develop functionalities based on the product requirements
* Build common libraries
* Design and implement various supporting tools as needed
* Collaborate with cross-functional teams to design, develop and delivery new features

### Why it would be awesome to work with us
* 13th month bonus
* Free Grab to work at a beautiful office in D1 with free in-office snack, coffee, Apple laptop, extra monitor etc...
* 20 days off annually + 10 national holidays
* Chrismas leave (25 Dec) + Vietnamese Family Day (28 Jun) + Birthday leave
* Premium Private health insurance package
* Flexible working hours. Don't let 9 to 5 limit you. You want to go to Coffee House to work, fine. Want to stay home to fix exploded oven, totally cool.

### Interesting engineering projects
* Will be discussed in an interview.

### Contact

Email: trung@returvis.com, skype: nguyen.huy.ky.trung

**Comment by fuatto** [comment]
@junnhk bạn ơi, kiểm tra lại thông tin title giùm mình đang không đúng format, sau đó update lại dùm mình.
