### ISSUE TITLE
French Start up - Senior Backend Golang - HN, HCM, Remote - FT

### ISSUE THREAD

**Issue by lamducduong184** [golang-vietnam/job_board#42]
## Location

* Saigon, Hanoi, Vietnam
* Remote

## Salary Expectation

* $up to 3000$ gross/month + bonus, Negotiation

## Requirements
* Senior Golang Developer
* 1+ years Software Engineering experience

### Ideally

* Experience with: Kubernetes, Docker, Terraform, Nosql, Cloud technology, Load balancer (NGINX, HAProxy, NLB, ALB)
 
### Responsibilities

Great power comes with great responsibilities!

### Why it would be awesome to work with us

A French startup with many experts in AI + BigData, IoT

### Contact
FB: https://www.facebook.com/duong.lam.1044/
Email: caothianh0810@gmail.com (0942492607)

**Comment by fuatto** [comment]
@lamducduong184 , bạn ơi kiểm tra lại title đang chưa đúng format, sau đó update lại dùm mình

**Comment by lamducduong184** [comment]
@fuatto: Mình đã viết lại title theo format rồi bạn ơi. Có gì cần chỉnh sửa nữa không bạn?
