### ISSUE TITLE
Gapo - Middle/Senior Backend Dev ( Golang ) - Ha Noi, HCM - FT

### ISSUE THREAD

**Issue by KyAnh1998** [golang-vietnam/job_board#45]
## Location

* Hanoi, HCM, Vietnam

## Salary Expectation

* $1500-2000/month

## Requirements

* Proficient in source code management tools: GIT
* Can work under high pressure on deadlines as well as product quality
* The ability to be well and proactive in work, has a high sense of responsibility to complete the assigned work
* Have experience in building Microservices running on Kubernetes or Swarm is a great plus
* Have knowledge about distributed system is a great plus
* Experience in Big Data (Spark, Hadoop) is an advantage
* Knowing Amazon Web Services (AWS), CI/CD is an advantage
* Knowledge of optimal handling Performance, Security is an advantage

### Must Have

* Experience working with MySQL, Redis, MongoDB (RabbitMQ & Kafka is a plus)
* Have knowledge of OOP, RESTful, Microservices, Design Patterns
* Solid knowledge of Golang

### Ideally

* Experience with Golang

### Why it would be awesome to work with us

* Meaningful work with passionate colleagues
* Attractive compensation, regular assessments and salary reviews
* 13-month & performance bonus
* 15 to 20+ paid day off per year
* Attractive benefits for team activities
* Very nice & open office with full of accessories for recreational activities
* An environment where you can be best of yourself, grow with us and together we make it works.
    
### Contact
Homepage: https://www.gapo.vn/login
Email: hr@gapo.vn
Telegram or zalo: 0971539691 ( Ky Anh )

**Comment by KyAnh1998** [comment]
Mọi người add zalo 0971539691 hoặc gửi CV về địa chỉ mail: hr@gapo.vn để mình liên lạc trao đổi công việc nhé!

**Comment by fuatto** [comment]
@KyAnh1998 phiền em sửa lại nội dung issue như mô tả ở tab code nhé, sẽ được lợi ích là bài được post lên đây https://golang.org.vn/  (như những issue khác)

**Comment by KyAnh1998** [comment]
> @KyAnh1998 phiền em sửa lại nội dung issue như mô tả ở tab code nhé, sẽ được lợi ích là bài được post lên đây https://golang.org.vn/ (như những issue khác)

Vâng ạ
