### ISSUE TITLE
Manabie Vietnam - Fullstack Engineer (Golang/ ReactJs) - District 1, HCMC - FT

### ISSUE THREAD

**Issue by duytran1993** [golang-vietnam/job_board#47]
## Location

15th Floor, 180 Nguyen Cong Tru, Nguyen Thai Binh Ward, District 1, HCMC

## Salary (gross):

- 1300$ max for Junior
- 1800$ max for Middle level
- 3000$ max for Senior level

## Requirements

- Be a sponge, absorb new knowledge and gain new experiences.
- Willing to learn Golang, Vue.js, React.
- Willing to learn about the mobile ecosystem.
- Willing to learn SQL databases.
- Strong ability to analyze.
- Organizational skills and attention to detail; time management skills.
- Strong collaborator, able to contribute to a variety of tasks.
- Excellent written and verbal communication skills.
- Creative and independent problem solver

## Skills

- Golang Or NodeJs
- gRPC

### Must Have

* Exp with any Backend programming languages.
* Exp with Golang is a plus.

### Responsibilities

Learn learn learn! We are here to share our knowledge and experience, and you are here to absorb it. And hopefully afterward, you can:
- Develop backend & frontend features.
- Create detailed, comprehensive and well-structured test plans and test cases.
- Design, review and execute tests for backend & frontend apps.
- Identify, record, document, track & prioritize bugs.
And of course, be a part of the team.

### Why it would be awesome to work with us

- Probation: 2 months (100% full-time salary).
- Health Insurance package.
- Role rotation opportunity.
- 14 days Paid Leave Annually.
- Young, dynamic and cooperative working environment.

### Contact

Our website: [**HERE**](https://manabie.com/)
Our stories: [**HERE**](https://vietcetera.com/en/manabie-a-startup-in-pole-position-to-disrupt-seas-legacy-education-industry) and [**HERE**](https://cafebiz.vn/takuya-homma-va-startup-manabie-tan-binh-dang-gom-tren-tren-dau-truong-ed-tech-viet-nam-va-chau-a-20200801150517399.chn)

Email: dylan.tran@manabie.com

**Comment by fuatto** [comment]
@duytran1993 phiền anh sửa lại title giúp em - theo format ở như mô tả ạ

**Comment by duytran1993** [comment]
> @duytran1993 phiền anh sửa lại title giúp em - theo format ở như mô tả ạ

Hi @fuatto ,

All done Phát nhé. Cảm ơn bạn đã hướng dẫn.
