### ISSUE TITLE
bTaskee Vietnam - Fullstack Developer (Golang) - District 10, HCMC - FT

### ISSUE THREAD

**Issue by bTaskee347** [golang-vietnam/job_board#51]
JOB DESCRIPTION
You will be responsible for:

Be in charge of architecturing, implementing and maintaining core backend features of our micro-services.
Working with the founder/product owner and project manager.
Contribute idea and play role in the growth of the company.
Enjoy great career growth opportunities.

JOB REQUIREMENTS
Senior in Golang with at least 2 years.
Basic knowledge of API, Web, Micro-service.
Basic knowledge of Nodejs.
Git.
Passion for writing great, simple, clean, efficient code.
Basic Knowledge of databases (Mongo, SQL,…).
Appreciated: Docker, k8s.

BENEFITS
We provide training to help you catch up with the current team .
All the employee’s benefits required by the Government.
Work in a startup environment where Innovation, Passion, Openness and Trust are at its core .
Salary increases every 6-12 months .
Bonus 13th-month salary .
Monthly team building event .
Company trip every year!
Learn new thing every week! We encourage our employee to spend 1 day a week to learn new stuffs.

Contact
Our website: https://www.btaskee.com/en/careers/senior-golang/
Email: hr@btaskee.com

**Comment by fuatto** [comment]
@bTaskee347 , bạn update lại dùm mình  phần mô tả cho đúng format nha, format đang xài là Markdown, cách nhanh nhất là bạn có thể copy bên  tab <Code> phần hướng dẫn rồi sửa lại content phù hợp
