### ISSUE TITLE
Fetch Tech - Senior Golang Developer - HCMC - PT

### ISSUE THREAD

**Issue by JunnieNguyen** [golang-vietnam/job_board#52]
## Location

* 42B Ho Ba Phan Street, Phuoc Long A Ward, District 9, Ho Chi Minh City.
* Part-time (3 months)

## Salary Expectation

* 1300$ - 2500$/month or rangge

## Requirements

* 4+ years of software development experience (with at least 2 years in Ruby on Rails/Golang).
* Good UI/UX design sense and able to develop designs in HTML/CSS/JS.
* Familiar with at least one front-end UI framework: AngularJS, ReactJS, EmberJS
* Familiar with linux system administration and provisioning systems using Amazon Web Services.
* Able to apply good security practices.
* Able to communicate by English.

### Nice to have

* Familiar with and passionate about BitCoin and crypto currencies, its network and protocol.
* Able to code in multiple languages: Java, Scala, Golang, Ruby.

### Responsibilities

* Full-stack developer to maintain and develop online services
* Work closely with the product development team to improve our platforms and contribute feature ideas and designs (visual & conceptual) for our website, mobile and web and applications.
* Participate in user testing on production. 

### Why it would be awesome to work with us.

* Onsite Singapore opportunity.
* MacBook for working.
* Attractive salary and annual salary review
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese
* Extensive on job training, you will always have a chance to work with new emerging technologies
* Full social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th month salary.
* Enjoy diversified activities: Happy time every day, Monthly Team-building, Company trip, Play Game (PlayStation, board games), Play Sport (Football, Badminton...).

### Contact

Email: dungnguyen@fetch.tech
Skype: dungphuongdh
Telegram: JunnieNguyen

**Comment by fuatto** [comment]
@JunnieNguyen , phiền bạn sửa lại dùm mình là HCM-PT ở title nha vì như vậy format xài chung để load thông tin lên page

**Comment by JunnieNguyen** [comment]
Hi anh @fuatto , Em đã update lại phần title của job rồi ạ. Em cảm ơn anh đã nhắc nhở em ạ!
