### ISSUE TITLE
FETCH TECH - Junior Fullstack Ruby on Rails/ NodeJs - Hanoi - FT

### ISSUE THREAD

**Issue by JunnieNguyen** [golang-vietnam/job_board#54]
## Location

* 3rd Floor, Dai Phat Building - Lane 82, Duy Tan Street, Dich Vong Hau Ward, Cau Giay District, Vietnam
* Full-time

## Salary Expectation

* 1200$/month 

## Requirements
* Have a Bachelor’s Degree in Computer Science, Info Technology or related subjects. 
* Have a minimum 2-3 years of experience in web development. 
* Experience with Shopify, and/or be able to learn and develop custom Shopify Theme using Shopify’s section theme architecture.
* Experience in developing and integrating external APIs with Shopify, as well as other servers.
* Highly experienced in Ruby/Ruby on rails or Node.js or any compatible server-side language.
* Proficiency with HTML5, CSS3 and Javascript/JQuery. 
* Understanding and usage of relational and non-relational databases (GraphQL for Shopify).
* Experience with cloud computing architectures (AWS, Google Cloud or Azure) to operate both development, production servers. 
* Have experience in securing data infrastructure within Shopify platforms, development, production servers and other endpoints. 
* Strong communication skills in English (both written and verbal). 

### Ideally

* Experience working in retail and with online/e-commerce industry

### Responsibilities

* Develop overall architecture of Shopify-based website.
* Work closely with Product Managers, Digital Marketing and Online/E-commerce Operations team to enhance UI/UX experience.
* Propose, develop and launch new features on the Shopify-based website.
* Lead and manage any special projects from conceptualisation to implementation.
* Maintain quality and ensure responsiveness of Shopify-based website.
* Ensure website is optimised for cross-browser/cross-platform compatibility.
* Provide consolidated sales reports from various data channels.
* Write code integrity and organization to ensure it’s scalable, maintainable, and reusable.
* Ensure data security across all platforms, in line with Singapore’s.
* Personal Data Protection Act.

### Why it would be awesome to work with us
* Onsite Singapore opportunity.
* Attractive salary and annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Extensive on job training, you will always have chance to work with new emerging technologies.
* Full social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th month salary.
* Enjoy diversified activities: Happy time every day, Monthly Team-building, Company trip, Play Game (PlayStation, CS Go), Play Sport (Football, Badminton...).   

### Contact

Skype: dungphuongdh
Email: dungnguyen@fetch.tech

**Comment by tieubao** [comment]
This is not a board for Node and Ruby
