### ISSUE TITLE
DTAC - Senior Golang Engineer -  Remote/HCM - FT

### ISSUE THREAD

**Issue by maya1554** [golang-vietnam/job_board#56]
## Location
* Remote

## Salary Expectation

* From 1500$

## Requirements
* From 2 years work experiences with Golang
*  Understanding one or more programming language (PHP/NodeJS is minimum)
* Familiarity with MongoDB and MySQL
* Experience with AWS ecosystem
* Minimum of 3 years experience

### Responsibilities
* Architecture and design of highly available/scalable backend services along with tech leads
* Design and write well-structured, easily maintainable, and thoroughly tested code
* Works with product team to refine product requirements
* Provide internal support and scalability of our engineering environment

### Contact

Email: duyen.talentseeker@gmail.com
Skype: dang.duyenna
Whatsapp: +84978901277

**Comment by fuatto** [comment]
@maya1554 Bạn kiểm tra lại title giúp mình, bạn có thể tham khảo các job offer acceptedd ở dưới làm mẫu nha

**Comment by maya1554** [comment]
> @maya1554 Bạn kiểm tra lại title giúp mình, bạn có thể tham khảo các job offer acceptedd ở dưới làm mẫu nha

Mình đã sửa, ad check giúp mình nhé
