### ISSUE TITLE
DTAC-Tech Lead - HCM remote - FT

### ISSUE THREAD

**Issue by maya1554** [golang-vietnam/job_board#57]
## Location
* Remote

## Salary Expectation

* From 2000$

## Requirements
* Understanding Two or more programming language (PHP/NodeJS at the minimum)
* Minimum 2 years experience in Golang
* Must communicate well in English
* Familiarity with MongoDB and MySQL
* Experience with AWS ecosystem
* Minimum of 5 years experience

### Responsibilities

* Architecture and design of highly available/scalable backend services
* Design and write well-structured, easily maintainable, and thoroughly tested code ∙ Works with product team to refine product requirements
* Provide internal support and scalability of our engineering environment
* Act as team player.
* Lead and Manage Backend team.

### Contact

Email: duyen.talentseeker@gmail.com
Skype: dang.duyenna
Whatsapp: +84978901277

**Comment by fuatto** [comment]
@maya1554 Bạn kiểm tra lại title giúp mình, bạn có thể tham khảo các job offer acceptedd ở dưới làm mẫu nha
