### ISSUE TITLE
Nara Reading Pte. Ltd. - Senior Golang Engineer(interns are also welcome) - TPHCM/Remote - PT

### ISSUE THREAD

**Issue by mr-chainblockz** [golang-vietnam/job_board#59]
## Location

-   Remote or HCMC

## Salary Expectation

-   around $US 10 / hours depending on the experience

## Requirements

-   Experience working with MySQL, Redis, MongoDB (RabbitMQ & Kafka is a plus)
-   Have knowledge of OOP, RESTful, Microservices, Design Patterns
-   Proficient in source code management tools: GIT
-   Can work under high pressure on deadlines as well as product quality
-   The ability to be well and proactive in work, has a high sense of responsibility to complete the assigned work
-   Have knowledge about machine learning is a great plus
-   Solid knowledge of Golang
-   Knowing Google Cloud, Amazon Web Services (AWS), CI/CD is an advantage
-   Knowledge of optimal handling Performance, Security is an advantage

### Job Description

-   We are looking for experienced backend developer to join our dynamic teams, and build an awesome BackOffice and API for Nara Reading App. You will have opportunity to contribute and resolve interesting problems in machine learning such as OCR, sycnthetic voice ....
-   Design and develop high-performance API and backend service
-   Design and optimize Database design
-   Maintain a high-quality robust codebase
-   Actively research and apply new technology and toolset

### Why it would be awesome to work with us

-   Remote, flexible, pay on working hours
-   Work on a meaningful product in education for young kids
-   An environment where you can be best of yourself, grow with us and together we make it works.

### Contact

Homepage:  [https://nara.sg](https://nara.sg)  
Email:  [hi@nara.sg](mailto:hi@nara.sg)  
Phone or zalo: 0979055563 ( Mr. Quang Nguyen )  
Messenger: [Nara Reading App](https://www.messenger.com/t/narareadingapp)

**Comment by fuatto** [comment]
@mr-chainblockz Bạn kiểm tra lại title giúp mình, bạn có thể tham khảo các job offer acceptedd ở dưới làm mẫu nha, phần 
(interns are welcome to apply also) bạn có thể là: ```<tên-công-ty> - <Senior...(interns are ...)> - <TPHCM/Remote> - PT``` nha, vì nếu không đúng format thì không load data lên page golang.org.vn được.

**Comment by mr-chainblockz** [comment]
Thanks @fuatto. Done.
