### ISSUE TITLE
Plus Team Global Company - Senior Golang Blockchain Developer - HCM/HN - FT

### ISSUE THREAD

**Issue by datvo1988** [golang-vietnam/job_board#60]
## Location

* Saigon, Vietnam, Remote

## Salary Expectation

* Salary up to 2500$ USD

## Requirements

- At least 7 years of software development experience
- Experience with development in Golang
- Experience in web development (html, css, js)
- Minimum Bachelors Degree in IT, Engineering or Computer Science from a top tier university
- Strong communication skills, able to write, read and speak English or Chinese well.
- Familiarity with blockchain technologies is a plus

## Responsibility:
- Develop, test and maintain blockchain based payment systems
- Develop API and web interfaces
- Design system flow, update documentation
- Assist clients with integration of payment systems
- Work with a highly professional team of blockchain experts to develop high quality payment systems

### Why it would be awesome to work with us
"A leading blockchain payment service is looking for talented engineers to join the team. Good benefits, fun environment, work with smartest people in the industry"

### Contact

Homepage: https://plusteam.io/
Whatapp or Zalo: +84931959588
Email: infor@plusteam.io

**Comment by fuatto** [comment]
@datvo1988 em check + sửa lại theo title mẫu có trong readme bên tab Code nhé

**Comment by datvo1988** [comment]
> @datvo1988 em check + sửa lại theo title mẫu có trong readme bên tab Code nhé

yes a Đạt Võ đây em Phát Phát
