### ISSUE TITLE
VieON - Backend Engineer & DevOps (6 vacancies) - HCM - FT

### ISSUE THREAD

**Issue by ducminhgd** [golang-vietnam/job_board#61]
## Location

* 222 Pasteur, Ward 6, District 3, Ho Chi Minh City

## Salary Expectation

* Competitive

## Requirements

* Go or Python.
* Having knowledge in one of these Databases: MySQL, PosgresQL, Mongo.
* Caching: Redis, Memcache.
* Docker
* CI/CD
* Having knowledge in Microservices and OTT is a plus
* It's a plus if you have knowledge in any of these: Lua programming, K8S, Unit Test, Elastic Search, Message Queue

### You’ll be responsible for

* Building Services of an OTT platform.

### Contact

* Mr. Giã Dương Đức Minh (R&D Manager) minh.gia@dzones.vn
* Ms. Lê Thị Hoàng Oanh (Senior HRBP) oanh.le.hoang@dzones.vn

**Comment by fuatto** [comment]
@ducminhgd , bạn check lại dùm mình title format đang không đúng với mẫu nha

**Comment by ducminhgd** [comment]
> @ducminhgd , bạn check lại dùm mình title format đang không đúng với mẫu nha

Mình đã sửa lại. Sẵn tiện cập nhật vị trí và số lượng.

**Comment by nguyenphamquangtue** [comment]
bạn ơi cho mình hỏi job này còn ko bạn
