### ISSUE TITLE
[HN - FREELANCE] GOLANG  TỪ MIDDLE

### ISSUE THREAD

**Issue by dongtuyetnhung** [golang-vietnam/job_board#66]
Em chào cả nhà,
Em đang tìm kiếm Golang developer - từ 2 năm kinh nghiệm,
Bên em đang có 2 hình thức:
- Freelance 3 -6 tháng
- Nhân viên chính thức với đầy đủ chế độ và hợp đồng dài hạn
- Lương upto 2500$ ạ
Các anh quan tâm vui lòng contact với em qua email:
nhung.dong@ntq-solution.com.vn ạ

**Comment by fuatto** [comment]
@dongtuyetnhung phiền bạn đọc và làm theo hướng dẫn ở tab <> Code nha, vì phải làm đúng format thì thông tin job mới lên page golang.org.vn được
