### ISSUE TITLE
[HCM - TIKI] BACKEND - GOLANG

### ISSUE THREAD

**Issue by Thanhtk** [golang-vietnam/job_board#68]
**Location**
Quận 10, TPHCM

**Requirements**
- Strong programming experience with one of Python/PHP/Java.  Strong programming experience on Golang is a plus.
- Knowledge about RESTful API and databases as MySQL, PostgreSQL, Redis.IO, Elasticsearch…
- Understanding of system design and tuning for high performance, scalability and reliability.
- Deep knowledge of latest trends in software engineering best practices - code reviews, code quality, CI/CD, monitoring, multithreading and memory management
- Be aggressive and proactive to get things done.
- Strong problem-solving skill and Data driven mind-set
- Customer-oriented and has a high standard of quality.

**Must Have**

 Strong programming experience with one of Backend language

**You’ll be responsible for**

Work with Product Owner to understand the requirement and build the product within aligned timeline
Work with QC team to deliver bug-free product and also contribute for automation testing
Provide last-tier support for assigned product lines
We have a strong team with a diversified background and a keen interest on being the best-in-class e-commerce. You will gain more domain knowledge in what is probably one of the hottest IT sectors right now and have chances to encounter and solve challenging problems on a large scale.

Since Tiki has become one of Vietnam's prime e-commerce websites, Supply Chain and Logistics plays a vital role in the remarkable success of Tiki along with the establishment of TikiNow Smart Logistics. At TikiNow Smart Logistics, we value the morale of customer-focused where instead of rejecting a customer's request we always suggest a better sustainable solution with Technology at its heart. Our vision is to become the best-in-class business with a continuous improvement to deliver innovative services that meet the customer's need while creating business success.

As a member of the Operation Product department - Inventory team, you will work on various solutions to develop the Order Routing Services which is one of the core services of Tiki. Order Routing Service is a function utilized for routing orders to the right warehouse with optimal delivery time and cost. With several fulfillment centers across the country, 64 provinces and a combination of 7 fulfillment types and business types behind, routing an order is a sophisticated action which is processed by ORS in less than a second. However, we never stop improving our service in order to serve hundreds of orders and customers, that is the reason we need your participation in our team to set another milestone for our success.

**Benefits**
Inside our engineering team:

We iterate constantly. There's no such thing as the best version of anything, just a constant stream of improvements and tests.
We move fast, really fast. Major changes can be executed in a few days, many times just a few hours.
We have a data-informed mindset. We try to use data to inform our decision as much as possible.
We are independent. Most of the time, your team will not need technical assistance from other teams.
We take risks. We're not afraid to challenge "best practices".
Our attractive offers include:

Open communication with passionate and experienced members.
Challenging working environment.
Easy access to the library with tons of startup, product, UX, coding... books.
Private healthcare insurance.
Annual health check-ups.
Special internal programs for Tikiers when shopping on Tiki.vn (free ship TikiNow service, discount...).
Internal events to bond our mutual understanding & spirit such as team building, team outing, Tiki's birthday, year-end party...
New & beautiful office with a pantry room (with bar), entertainment & gymnastic equipment, yoga rooms, a library and an open space facilitating cross-department communication.
Competitive salary and performance review

**Contact**
Skype: bnamthanh

**Comment by fuatto** [comment]
@Thanhtk phiền bạn đọc và làm theo hướng dẫn ở tab <> Code nha, vì phải làm đúng format thì thông tin job mới lên page golang.org.vn được! Title đang không đúng, cách dễ nhất là bạn copy phần mẫu rồi sửa lại phần content cho đúng ý muốn là được
