### ISSUE TITLE
Freelancer thị trường nhật - BACKEND GOLANG

### ISSUE THREAD

**Issue by gotech-dev** [golang-vietnam/job_board#69]
Hi all

Bên mình đang cần tuyển dev có kinh nghiệm làm backend ngôn ngữ GO
để làm dự án cho thị trường Nhật.

## Location
* Vietnam
* Remote

## Salary Expectation

* Tính theo giờ ( 2 bên thỏa thuận)

## Requirements
* Có kinh nghiệm lập trình ngôn ngữ GO

## Skills
GO language
AWS

### Contact
Vui lòng liên hệ skype để trao đổi chi tiết về dự án 
Skype : ngaidaictcd

**Comment by fuatto** [comment]
@gotech-dev phiền bạn đọc và làm theo hướng dẫn ở tab <> Code nha, vì phải làm đúng format thì thông tin job mới lên page golang.org.vn được!
