### ISSUE TITLE
[Mễ Trì] NTQ Solution - Golang 2+ years Exp - upto 2500$

### ISSUE THREAD

**Issue by Mimia135** [golang-vietnam/job_board#70]
## Location

* Hanoi, Vietnam
* Fulltime

## Requirements
* Golang
* 2+ years experience

### Contact

Skype: my.nguyen_48
Email: my.nguyen@reco-vn.com

**Comment by fuatto** [comment]
@Mimia135 phiền bạn đọc và làm theo hướng dẫn ở tab <> Code nha, vì phải làm đúng format thì thông tin job mới lên page golang.org.vn được
