### ISSUE TITLE
 SSI Securities Corp - Software Developer (GO) - Negotiable - HCM/HN - FT

### ISSUE THREAD

**Issue by lamhoang-nhatphuong** [golang-vietnam/job_board#73]
## Location

* Saigon / Hanoi, Vietnam
* Fulltime

## Salary Expectation

* Attractive

## Requirements

SSI Securities Corporation is looking for Software Developers (GO language Or Python, Java, .Net, C/C++) - On-board after Tet holiday.

* University degree in Computer Science, Information Technology or related subjects
* 3+ years of software product development experience (at least 6 months with Go language). We also welcome strong candidates having fewer years of experience as well, please tell us why "year" doesn't matter.
* Solid technical skill, you talk confidently about Go (or Python, Java, C/C++) and are willing to learn new technologies. Big plus if you can talk broader than that.
* Knowledge about gRPC / REST API and databases such as PostgreSQL, Google Cloud Spanner, Cloud Firestore (or MongoDB or any NoSQL database), etc.
* Understanding of system design and tuning for high performance, scalability and reliability.
* Experience with Microservices and / or Cloud Native architecture is a plus.
* Experience with NATS or Kafka messaging is a plus.
* Experience with DevOps or Site Reliability Engineering and CI/CD is a plus.
* Understand the balance between technical and business decisions.

### Responsibilities

* Participate in all phases of the development life-cycle.
* Optimize the system for reliability and performance.
* Write high-quality, clean, elegant, and maintainable code.
* Understand the product thoroughly, constantly optimise the product, identify and fix problems, improve stability and user experience.
* Analyse requirements, design and develop functionalities based on the product requirements.
* Build common libraries and backend services.
* Design and implement various supporting tools as needed.
* Collaborate with cross-functional teams to design, develop and deliver new features

### Why it would be awesome to work with us

* Highly competitive remuneration package: Attractive monthly salary, 13th month salary, KPIs cash bonus, Public holiday cash bonus, Birthday gift, Lunar new year gift,...
* Premium AON health care insurance and full labor insurance
* 14 days Annual leave
* Luxury team-building trip and varied engagement activities
* Joining the leisure clubs: Football, E-Sport, Running, Gym, Yoga....
* Fully sponsored training to build your career
* Professional, open-minded and supportive working environment
* Working time: Mon - Fri | 08:00-17:00

### Contact
Email: nhatphuong.lamhoang@gmail.com
Subject: [SSI - Software Developer - Your Name]

**Comment by fuatto** [comment]
@lamhoang-nhatphuong phiền bạn sửa lại title dùm mình nha, phần "Negotiable" có thể đem xuống phần salary expectation nha vì phải làm đúng format thì thông tin job mới lên page golang.org.vn được
