### ISSUE TITLE
Money Forward Vietnam - Software Engineer (Golang) - HCMC - FT

### ISSUE THREAD

**Issue by nguyentoloan** [golang-vietnam/job_board#75]
## Location
* Ho Chi Minh City 

## Salary Expectation
* Extremely competitive

## Requirements
* 2+ years of Golang experience

### Must Have
* Experience in reviewing code
* Experience in writing good unit tests

### Ideally
* Experience with frontend development (ReactJS, VueJS, jQuery)
* Can communicate in English

### Responsibilities
* Develop and design service
* Design database schema
* Write clean and maintainable code
* Discuss and debate with other team members to find optimal solutions

### Why it would be awesome to work with us
* Salary review: Twice a year
* Bonus: 13th-month salary
* Paid leave: 15 days in total, Maternity leave for partner (extra 5 days)
* Awards: Monthly Culture Hero, Half-year MVP for excellent members
* Activities: Company trip, Year-end party, Half-year party, team-building, happy hour, etc...
* Devices: MacBook Pro + Dell Monitor
* Working hour: Monday to Friday (working hour starts from 8am to 9am)
* Health care: Annual health check
* Insurance: Social Insurance, Health Insurance, Unemployment Insurance (company will pay for full salary); Voluntary health insurance & accident insurance (Bao Viet Tokio Marine Insurance 24/7
* Training: External or internal training courses; Internal workshop; Support Attending Conference; Scrum training; Order books based on member's requests
* Others: Grab expenses on the party day; Club activities, playstation, billiard, etc… Free bike parking, fruits and coffee

### Contact
Email: nguyen.thi.to.loan@moneyforward.vn
Skype: nguyentoloan2009

**Comment by fuatto** [comment]
@nguyentoloan , phiền bạn sửa lại format JD cho đúng với bên mô tả ở tab <Code> nhé, tip là bạn có thể copy form rồi sửa lại nội dung, như vậy thông tin mới lên được page golang.org.vn nhé

**Comment by nguyentoloan** [comment]
Hi, I have updated the issue follow the format. Please let me know if I still have other thing to edit. Thank you so much.

**Comment by nguyentoloan** [comment]
Hi,
Mình đã sửa lại tin đăng theo format. Phiền admin xem lại giúp mình nhé.
Nếu có chỗ nào cần sửa lại, nhờ admin báo mình với ạ.
Cảm ơn mọi người.

Brs,
Loan
