### ISSUE TITLE
ORIENT SOFTWARE - Senior Golang Engineer - HCM - FT

### ISSUE THREAD

**Issue by phungmai04** [golang-vietnam/job_board#76]
## Location

* Saigon, Vietnam
* Fulltime

## Salary Expectation
* $2000

## Requirements
* Golang
* Microservice
* RabbitMQ
* gRPC
* 4+ years Software Engineering experience

### Responsibilities

* Improving our core technical platform. Making it more stable, more performant, easier to work in and more scalable.
* Building features that provide quick value to users.
* Contribute to all stages in the product life cycle. Design, implementation, testing, deployment, and monitoring
* Learn and try new things to feed your thirst for knowledge and experience
* Work with the hardware and dev tools of your choice

### You’ll be responsible for

* Build an application about Fintech

### Contact

Homepage: https://www.orientsoftware.com/careers/
Email: phung.mai@orientsoftware.com

**Comment by fuatto** [comment]
Mình có sửa lại format cho title 1 tí (đúng form vậy mới lên page golang.org.vn được)
