### ISSUE TITLE
[Remote] Lead/Senior Engineer in Blockchain Copany_ from $3500

### ISSUE THREAD

**Issue by Mimia135** [golang-vietnam/job_board#78]
## Location

* Vietnam
* Remote

## Salary Expectation

* from $3500/month 

## Requirements
* C++ , Solidity, web3.js, rust, nodejs, 
* TDD, writing tests and unit testing (automated testing a plus)
* DevOps
* 4+ years developing software in blockchain 

### Must Have

* solidity
*At least 4 years leading or managing others

### Ideally

* Knowledge of Cryptography 

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Build a world-class development team. Ensure the team adheres to the defined development methodology.  Ensure the team writes clean, readable, and maintainable tested code.  Facilitate auditing and optimisation of code for performance issues, stability, speed, and scalability. Create modular code and libraries for future usage.  To learn, grow, and improve with the team throughout the process.  

### You can bring

* A good eyes for design
* A good analyis skill

### Contact

Homepage: job.reco-vn.com
Email: my.nguyen@reco-vn.com

**Comment by fuatto** [comment]
@Mimia135 phiền bạn sửa lại title của issue cho giống với format nha, bạn có thể tham khảo của các issue khác có label <accepted>, đúng format mình mới lên data JD lên page golang.org.vn được
