### ISSUE TITLE
Axon Hiring Event: Software Engineers (all levels)

### ISSUE THREAD

**Issue by mpham11** [golang-vietnam/job_board#83]
## Our mission is to protect life.

Axon - We’re out to make the world a safer place by solving big problems and taking on the public safety challenges of our time. From our company's inception building the TASER device to a full suite of hardware and software solutions, we are focused on providing police agencies with state-of-the-art devices and services they need to successfully serve and protect us. In the next few years, we're going to eliminate the burden of paperwork in policing, so officers can increase the time they spend building relationships and serving in their communities. We’ll put video at the heart of police records so our justice system can get to the truth faster. And we won't stop innovating until the bullet is rendered obsolete.

It’s a big mission, but it’s one we’ll pursue relentlessly every single day.

Axon has lead the global effort to protect life and through through electric weapons, body cameras, a number of real-time sensors, public safety software products and AI tools. Axon is uniquely positioned to tie together every aspect of an incident in order to help law enforcement agencies better prepare for what might happen, respond efficiently and effectively, deliver justice, ensure the well being of their officers, and increase the safety of their communities. Working together with our customers and product teams, you will build the foundation for Axon’s outcome-oriented data efforts.

## We're hosting a Hiring Event on Apr 5 - 9th and welcome all Software Engineers to join us. You will have the chance to:
Learn more about what Axon is doing
Interview and receive feedbacks within 24 hours
Work in an awesome office/working environment with the latest technologies.
Have the competitive salary and benefits including a great medical insurance plan for you and your family.
Have fun team activities and outings.

## Your Impact
As one of the early engineering leaders on the team, you will make key design decisions that will shape this product. You’ll create and maintain the data integration, management, and analytics platform alongside Axon’s newest public safety technology products. This platform will offer law enforcement administrators and crime analysts flexible access to key crime data, decision support, state and federal crime reports, and criminal investigation insights.

## Your Day-to-Day
Participating in code reviews and architecture design meetings
Owning and driving end-to-end features with Product and Design
Ensuring that your code hits a high bar for quality and performance
Partner with internal teams and agencies to make public safety data accessible and actionable.
Influence peers, advise senior leaders, coach and mentor junior team members.
Facilitate cross-team collaboration among engineers and contribute to the broader community of Axon engineers.

## Basic Qualifications
Bachelor’s degree in CS, engineering, or other quantitative field.
Highly technical with 2+ years of experience developing and maintaining end-to-end, high availability, high throughput web-scale data systems.
Frontend experience in Javascript, Typescript or similar
Backend experience in managed languages such as Java, Scala, Go, C#, or similar.
Demonstrated ability to make tough technical decisions based on requirements, constraints, and trade-offs.

## Preferred Qualifications
Bachelor's Degree in Computer Science, Engineering, or related field
You follow the latest in software engineering and open source technologies, and can intuit the fine line between promising new practice and overhyped fad
Industry experience working with SQL or NoSQL data stores
Good Linux/Unix/Mac experience
You love delighting end users and hunger for novel challenges

## Compensation and Benefits
Free lunch, gym, phone stipend, parking.
Flexible working hours.
Opportunities for training and rotations in the US.
Opportunities to ride along with real US police officers in real life situations, see them use technology, and get inspired.
_We are an equal opportunity employer and value diversity at our company. We do not discriminate on the basis of race, religion, color, national origin, gender, sexual orientation, age, marital status, veteran status, or disability status._

## HIRING PROCESS:
1. Application
2. Technical test / Homework
3. Onsite interview (4 hours at Axon Vietnam Office)

## HOW TO APPLY:
1. APPLY via the link 👉 https://boards.greenhouse.io/axon/jobs/4322399003 (at the end of the web) OR
2. Send your CV directly to email: recruitingvn@axon.com

If you have any question, feel free to leave us a message at recruitingvn@axon.com

**Comment by gopher5889** [comment]
tuyển dev all level mà lại yêu cầu ít nhất 2 năm kn là sao ạ ?

**Comment by fuatto** [comment]
chào @mpham11 , phiền bạn sửa lại format JD cho đúng với mô tả (có thể tham khảo theo 1 JD đã được accept), không đúng format thì thông tin sẽ không được tải lên golang.org.vn đâu
