### ISSUE TITLE
[Techub Software] - [Senior Golang - [FT/Saigon] - FT]

### ISSUE THREAD

**Issue by trangthupham02051998** [golang-vietnam/job_board#84]
## PARK 7 VINHOMES CENTRAL PARK 208 NGUYEN HUU CANH STR, BINH THANH DISTRICT,HCMC

* Saigon, Vietnam
* FT

## Salary Expectation

*  $1000/month - $2000/month
## Requirements
* Strong knowledge of Go programming language, paradigms, constructs, and idioms
*Knowledge of common Goroutine and channel patterns
*Experience with the full site of Go frameworks and tools
*Experience in EtherScan, UniScan is a plus
* Strongly understand OOP, design pattern.
*Able to write well-structured, extendable, and maintainable code.

## Skills

* Having a Product Mindset and good problem solving would be a big plus.
* Eager to learn new technologies.
* Good at English communication.
* Can-do-attitude and put the goals of the team before your own prestige.
* You are able and hungry to take on a lot of responsibility.

### Responsibilities

Details of job responsibilities will be discussed in the interview.

### Why it would be awesome to work with us
*Work with young and talented engineers with a great teamwork
*You will be proud of producing software applications that hundred of people are using every day
* Very attractive salary and annual salary review
*Opportunity for working remotely

### Contact

Mail:tranghr0205@gmail.com
Subject: [FT - Go - Name]
Skype: live:trangthupham02051998

**Comment by fuatto** [comment]
chào @trangthupham02051998  , phiền bạn sửa lại format JD cho đúng với mô tả (có thể tham khảo theo 1 JD đã được accept), không đúng format thì thông tin sẽ không được tải lên golang.org.vn đâu
