### ISSUE TITLE
Pionero tuyển Junior/Senior Fullstack/Backend

### ISSUE THREAD

**Issue by dominhhai** [golang-vietnam/job_board#86]
Công ty cổ phần Pionero (https://www.pionero.io) chuyên tư vấn, phát triển giải pháp công nghệ cho khách hàng Nhật Bản cần tuyển những key members đầu tiên để đặt nền móng cho công ty tại Hà Nội.
Địa điểm làm việc: Y-Nest Coworking Space, Tầng 4 TTTM V+, 505 Minh Khai, Hai Bà Trưng, Hà Nội 

👍 Quyền lợi:
- Được tham gia vào xây dựng công ty từ lúc sơ khai
- Được thách thức bản thân bởi những vấn đề kỹ thuật khó
- Có cơ hội được học hỏi, giao lưu với các kỹ sư đến từ các tập đoàn hàng đầu thế giới
- Cơ hội trở thành lãnh đạo trong công ty

⭐️ Junior/Senior Full Stack Engineer
Vai trò:
- Thiết kế kiến trúc hệ thống 
- Đảm bảo chất lượng kỹ thuật cho dự án
- Định hướng, quản lý nhóm đi đúng hướng kỹ thuật
- Triển khai, phát triển hệ thống 
 
Yêu cầu:
- Thành thạo lập trình 1 trong các ngôn ngữ C++, Python, Golang, Ruby, JavaScript…
- Hiểu biết về các phương pháp phát triển phần mềm
- Có hiểu biết về các mô hình và thành phần hệ thống
- Có kinh nghiệm thiết kế hệ thống
- Có kinh nghiệm DevOps, Cloud
- Yêu thích và thường xuyên cập nhật công nghệ mới 

⭐️ Junior AI Engineer 
Vai trò:
- Tìm hiểu, đọc paper và code về AI
- Phát triển thuật toán AI dựa theo tư vấn từ các chuyên gia 
- Hỗ trợ tích hợp AI vào hệ thống 

Yêu cầu: 
- Biết lập trình Python và sử dụng được các thư viện như pandas, scikit-learn, TensorFlow, Pytorch... 
- Có kiến thức về AI, học máy, học sâu 
- Có kinh nghiệm về cài đặt, triển khai thuật toán AI
- Có khả năng đọc hiểu paper AI bằng tiếng Anh

Mọi thông tin xin vui lòng gửi email vào contact@pionero.io

**Comment by fuatto** [comment]
chào @dominhhai , phiền bạn sửa lại format JD cho đúng với mô tả (có thể tham khảo theo 1 JD đã được accept), không đúng format thì thông tin sẽ không được tải lên golang.org.vn đâu
