### ISSUE TITLE
[GẤP] Golang Developer | Middle/Senior

### ISSUE THREAD

**Issue by nhatthanh2011** [golang-vietnam/job_board#87]
Công ty TNHH Phần mềm NSC cần tuyển Back-end developer sử dụng ngôn ngữ Golang.
Khách hàng Hàn Quốc, ứng viên phù hợp sẽ lead phần back-end của dự án. Sẵn sàng offer lương cao. Có thưởng dự án!

## Location
* Hanoi, Vietnam
* Remote

## Salary Expectation
20-40 tr

## Requirements
* Golang
* PostgreSQL
* 
### Contact
Email: ceo@nsc-software.com (0866639497) Gọi để trao đổi chi tiết

**Comment by fuatto** [comment]
chào @nhatthanh2011  , phiền bạn sửa lại format JD cho đúng với mô tả (có thể tham khảo theo 1 JD đã được accept), không đúng format thì thông tin sẽ không được tải lên golang.org.vn đâu
