### ISSUE TITLE
[Remote] Golang Developer_ $1700 - $2000

### ISSUE THREAD

**Issue by Mimia135** [golang-vietnam/job_board#93]
## Location

* Saigon, Hanoi, Vietnam
* Remote

## Salary Expectation

* $2000/month 

## Requirements
* Golang
* 2+ years Go experience

### Must Have

* Strong knowledge of Go programming language, paradigms, constructs, and idioms

### Ideally

* Experience with 

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Building a new Facebook

### You can bring

* A good eyes for design
* A good analyis skill

### Contact

Skype: my.nguyen_48
Email: my.nguyen@reco-vn.com

**Comment by fuatto** [comment]
chào @Mimia135 , phiền bạn sửa lại format JD cho đúng với mô tả (có thể tham khảo theo 1 JD đã được accept), không đúng format thì thông tin sẽ không được tải lên golang.org.vn đâu
