### ISSUE TITLE
Senior Software Engineer (Golang / Nodejs / .NET) - Up to $3,000

### ISSUE THREAD

**Issue by hlttai** [golang-vietnam/job_board#94]
## Location

* HCMC, Vietnam

## Salary Expectation

* up to $3,000

## Skills

* Experience with one of tech stack Golang / NodeJS / .NET
* Understanding of Agile methodologies and DevOps
* Excellent troubleshooting and communication skills
* Joined the startup/product team to build an e-commerce platform serving thousands of daily orders

## You’ll be responsible for

* Participate in backlog refinement/requirement analysis. 
* Collaborate with internal teams to produce software design and architecture
* Write clean, scalable, and high-performance code 
* Test and deploy applications and systems
* Revise, update, refactor and debug code
* Develop documentation
* Serve as a technical expert and provide support

## Why it would be awesome to work with us

* Join an amazing team to build one of the biggest e-grocery platforms in Vietnam

### Contact

Email: career@kyanon.digital

**Comment by fuatto** [comment]
chào @hlttai  , phiền bạn sửa lại format JD cho đúng với mô tả (có thể tham khảo theo 1 JD đã được accept), không đúng format thì thông tin sẽ không được tải lên golang.org.vn đâu
