### ISSUE TITLE
Senior Software Engineer (Golang / Nodejs / .NET) - Up to $3,000

### ISSUE THREAD

**Issue by LamAnhVu** [golang-vietnam/job_board#95]
### **Location**
Kyanon Production House, Saigon, Vietnam

### **Salary Expectation**
* $3000 Net/month

### **Skills**
- Experience with one of tech stack Golang / NodeJS / .NET
- Understanding of Agile methodologies and DevOps
-  Excellent troubleshooting and communication skills
- Joined the startup/product team to build an e-commerce platform serving thousands of daily orders

### **Responsibilities**
- Participate in backlog refinement/requirement analysis.
- Collaborate with internal teams to produce software design and architecture
- Write clean, scalable, and high-performance code
- Test and deploy applications and systems
- Revise, update, refactor and debug code
- Develop documentation
- Serve as a technical expert and provide support

### **Why it would be awesome to work with us**
- Join an amazing team to build one of the biggest e-grocery platforms in Vietnam
- Bonus structure + 13th month Bonus.
- Flexible working time: only 8 hours required as continual working-time at the office.
- 12 days Annual leave.
- Coffee and snacks provided.
- Holiday celebrations and parties for team members and family.
- Company trip, team building activities.

### **Interesting engineering projects**
- Experience working as a member of a small agile software development team, e.g. participating in planning sessions and interpreting user stories, doing code reviews, pair programming.
- Improve English skills. 
- Have a chance to study new technology, new domain through workshops, seminars, and conferences.

### Contact
Homepage: https://kyanon.digital/
Mail: career@kyanon.digital (0359.189.555 - Ms.Anh)

**Comment by fuatto** [comment]
chào @LamAnhVu  , phiền bạn sửa lại format JD cho đúng với mô tả (có thể tham khảo theo 1 JD đã được accept), không đúng format thì thông tin sẽ không được tải lên golang.org.vn đâu
